### ISSUE TITLE
assert.deepEqual hangs when comparing arrays if the array prototype was modified by Opal

### ISSUE THREAD

**Issue by s-leroux** [chaijs/chai#1153] opened 2018-04-09 00:11 UTC
Opal is a Ruby to JS converter. [opal-runtime](https://github.com/Mogztter/opal-node-runtime) by @Mogztter is a helper library providing the runtime environment to run Ruby->JS converted programs.

Apparently, it modifies the prototype of the standard objects in such a way assert.deepEqual hangs (presumably on a circular reference):

```
> require('opal-runtime')
> assert = require('chai').assert
> assert.deepEqual([1,2,3], [1,2]);
## Hang here
```

I assume other libraries modifying the standard object's prototype in a similar way could cause Chai to hang too.

Tested with node v8.9.4, opal-runtime 1.0.1 and chai 4.1.2

**Comment by demurgos** [comment] 2018-04-09 00:14
Maybe related to https://github.com/chaijs/deep-eql/issues/51

A fix would be to use `Function#apply` instead of the methods on the objects.

**Comment by s-leroux** [comment] 2018-04-09 00:41
Maybe @demurgos. Maybe not.

I tried to follow the code with the debugger. It does not _seem_ to be stuck in an infinite loop. But I also noticed Chai found 850 visible properties on arrays and 800 on functions. So the issue might "just" be caused by a combinatorial explosion.

**Comment by s-leroux** [comment] 2018-04-09 10:29
Very probably the same issue as https://github.com/chaijs/chai/issues/1109

**Comment by keithamus** [comment] 2018-06-09 16:12
Hey @s-leroux thanks for the issue.

I'm sure this is actually a duplicate of #1109. `assert.deepEqual` works with circular references, so it is likely that the issue is with `loupe`, as mentioned in #1109. I'll close this one, but thanks for filing this issue and please don't hesitate to open any new ones if you find anything new!

**Closed by keithamus** 2018-06-09 16:12 UTC
