### ISSUE TITLE
Assertion planning

### ISSUE THREAD

**Issue by Turbo87** [chaijs/chai#670] opened 2016-04-07 09:50 UTC
It might be useful to have assertion planning built into chai for async testing (see e.g. https://github.com/sindresorhus/ava/issues/25).

I currently imagine it working roughly like this:

```js
describe('something', function() {
    afterEach(function() {
        chai.verifyPlan();
    });

    it('works', function() {
        chai.plan(2);

        expect(true).to.be.true;
        expect([1, 2, 3])
            .to.contain(1)
            .to.contain(2);
    });
});
```

- `chai.plan(n)` sets an internal `assertionsPlanned` variable to `n` and resets `assertionsExecuted` to `0`

- each `expect(...)` call increments the `assertionsExecuted` counter
  - to make this work with the `should` interface we should increment in the `Assertion` constructor if a `planned` flag hasn't been set yet

- `chai.verifyPlan()` compared `assertionsPlanned` with `assertionsExecuted` and throws an error if they don't match
  - `chai.verifyPlan()` should also reset `assertionsPlanned` to `0` to make it work for following tests that don't use `chai.plan(n)`

**Comment by keithamus** [comment] 2016-04-07 09:55
Hey @Turbo87 thanks for the issue.

We have discussed this before in #94. As per that discussion, it's a little tricky to pull off because the logic of what an "assertion" is with Chai's fluent syntax is very different to simpler test frameworks like that of Ava, Tape, Tap, Qunit et al.

Having said that, #94 is still open so we can come to a consensus, so feel free to continue the discussion there. 

Closing this as its a dupe of #94

**Closed by keithamus** 2016-04-07 09:55 UTC
