### ISSUE TITLE
Deep equality issue on 4.1.2

### ISSUE THREAD

**Issue by mrkesh** [chaijs/chai#1039] opened 2017-09-06 10:11 UTC
Deep equality seems to have an issue in version **4.1.2** when test is ran on **phantomJS**

**Example**:
```
var a = {
   foo: 'bar'
};
Object.preventExtensions(a);

var b = {
   foo: 'bar'
};
Object.preventExtensions(b);
        
chai.assert.deepEqual(a, b);
```

**Error Message**:
```
Attempting to define property on object that is not extensible.
    defineProperty@[native code]
    setMap@node_modules/chai/chai.js:9558:28
    memoizeSet@node_modules/chai/chai.js:9608:20
    extensiveDeepEqual@node_modules/chai/chai.js:9728:13
    deepEqual@node_modules/chai/chai.js:9644:28
    assertEql@node_modules/chai/chai.js:1442:14
    methodWrapper@node_modules/chai/chai.js:7709:30
    deepStrictEqual@node_modules/chai/chai.js:4311:59
```

Example above works on 4.1.1

**Comment by shvaikalesh** [comment] 2017-09-06 10:39
Hey @mrkesh, thanks for the detailed issue.
It caused by wrong extensibility check, introduced in https://github.com/chaijs/deep-eql/pull/41.
Should be fixed by https://github.com/chaijs/deep-eql/pull/48.

**Closed** 2017-09-06 21:02 UTC
