### ISSUE TITLE
Cannot install chai with bower

### ISSUE THREAD

**Issue by adongy** [chaijs/chai#725] opened 2016-06-10 18:36 UTC
Hello,

I'm trying to install chai through bower (as there is a bower.json in the root directory it seems to be a supported path of installation).

Issue is that ignore contains the lib directory, so this require fails
https://github.com/chaijs/chai/blob/master/chai.js#L2
https://github.com/chaijs/chai/blob/master/bower.json#L16

Is this still supported?

Thanks.

**Comment by meeber** [comment] 2016-06-11 02:57
@adongy It should work. I just ran a basic test with bower and didn't run into any issues. That code you linked with the require on L2 is just browserify magic; it's not actually trying to load anything from the `lib` folder. Everything is self-contained within the chai.js file.

If you're still running into issues, could you provide a reduced test case via a public repo that demonstrates the error you're running into? Thanks! :D

**Comment by meeber** [comment] 2016-06-13 22:28
Gonna close this because I was unable to reproduce the issue, but will reopen if you can post a public repo demonstrating the problem.

**Closed by meeber** 2016-06-13 22:28 UTC
