### ISSUE TITLE
deepPropertyVal bug

### ISSUE THREAD

**Issue by pronebird** [chaijs/chai#505] opened 2015-08-16 21:20 UTC
Hi,

I found that deepPropertyVal is not able to compare two plain objects:

```coffee
expect = { _id: mongoObject._id.toString(), rating: 5, count: 1 }
assert.deepPropertyVal body, 'payload', expect
```

Got error:

```
Uncaught AssertionError: expected { Object (success, payload) } to have a deep property 'payload' of { Object (_id, rating, ...) }, but got { Object (_id, rating, ...) }
```

Input:
```
expect = { _id: '55d0fdce8a5c1c15035150bd', rating: 5, count: 1 }
body = { success: true, payload: { _id: '55d0fdce8a5c1c15035150bd', rating: 5, count: 1 } }
```

**Comment by keithamus** [comment] 2015-08-16 21:32
Hey @pronebird thanks for the issue.

This is because the last argument of `deepPropertyVal` should be exactly equal to the property, and in your case they're not (they're just deeply equal instead). To illustrate:

```js
expect = { _id: one._id.toString(), rating: 5, count: 1 }
body.payload === expect; // false
```

The way you'd do this within chai, is as follows:

```js
expect = { _id: one._id.toString(), rating: 5, count: 1 }
assert.deepEqual(body.payload, expect);
```

If you were using the expect api you could do the following, instead:

```js
expect = { _id: one._id.toString(), rating: 5, count: 1 }
expect(body).to.have.property('payload').and.to.deep.equal(expect);
```

I'm going to close this issue, because this is the intended behaviour, and you can test it using the above "workarounds".

**Closed by keithamus** 2015-08-16 21:32 UTC

**Comment by pronebird** [comment] 2015-08-16 21:33
@keithamus thank you!

**Comment by keithamus** [comment] 2015-08-16 21:34
You're welcome @pronebird. Feel free to post any other issues you see with using Chai, I hope you enjoy using it :smile:
