### ISSUE TITLE
.to.have.property not working on propertys which is an array

### ISSUE THREAD

**Issue by LukasOchmann** [chaijs/chai#999] opened 2017-06-29 07:26 UTC
So i use Chai (3.5.0) with Karma, Mocha and Sinon to test a Vue Application. I wrote a vue-component with a `data()` Method like this:
```javascript
data() {
   return {
     keywords: []
}
}
```

so the keywords schoud be empty when the vue component is rendered, to test this i used the `.to.have.property()` method with `'keyword'` and `[]` as arguments.

if i run my test i got this:

> expected { Object (keywords) } to have a property 'keywords' of [], but got [].

so is this a Bug or did i do something wrong?
I know i could do it like
`.to.have.property('keywords').that.equals([])` but it would be simpler to just do it with `.to.have.property()`

**Comment by keithamus** [comment] 2017-06-29 08:56
Hey @LukasOchmann thanks for the issue.

The cause of this is because the two objects you're checking `.equal` don't actually equal - they _look_ the same but are _two different references_ to _two different objects_. We have an assertion to help you though; `deep.equal()`

```js
expect({}).to.equal({}) // fails
expect({}).to.deep.equal({}) // passes!

expect({ foo: {} }).to.have.property('foo', {}) // fails
expect({ foo: {} }).to.have.property('foo').that.equals({}) // fails
expect({ foo: {} }).to.have.property('foo').that.deep.equals({}) // passes!
```

Hopefully this gives you enough to solve you issue. I'll close this for now, as this is not a bug in Chai, but feel free to add replies here and we'll answer them if and when we can 😄

**Closed by keithamus** 2017-06-29 08:56 UTC
