### ISSUE TITLE
Asserting on all items in an iterable with `.all`

### ISSUE THREAD

**Issue by ethanresnick** [chaijs/chai#1137] opened 2018-02-07 21:32 UTC
The desire for something like this was first raised in #410 as far as I can tell, but a concrete proposal was never really made there/didn't go very far.

My basic thinking is that chai already has an `all` modifier, but its power seem to be very limited at the moment (to just influencing the `keys` assertion). A natural extension of this would seem to be to use `all` to require that an assertion holds for all items in an iterable. 

I confess to not being familiar with how Chai is implemented, so I don't know if this would be possible to implement backwards compatibly (and/or if an exception would have to be made for `.all.keys` to preserve the current behavior). Maybe someone with more background can weigh in on the implementation options there. Here's the syntax that I think would be nice, though:

```
expect([a, b, c]).to.all.equal(3);
expect([a, b, c]).to.all.satisfy(it => it > 2);
expect([a, b, c]).to.all.throw(); // etc. can imagine any assertion after the all.
expect([a, b, c]).to.all.have.all.keys('a', 'b'); // posible?
expect([a, b, c]).to.all.have.any.keys('a', 'b'); // posible?
```

**Comment by meeber** [comment] 2018-02-10 19:06
Unfortunately, https://github.com/chaijs/chai-things (which seems to do exactly what you're looking for) is only compatible with very old versions of Chai. IIRC, part of the problem is a conflict between Chai's core `.all` and that plugin's `.all`. The last time I looked into this, I believe I formed the opinion that the plugin should probably pick a different keyword, like `.each`. I don't think we can support assertions like `expect([a, b, c]).to.all.have.all.keys('a', 'b');` where `.all` has multiple meanings based on context. Hopefully this type of conflict with plugins can be avoided in the future once https://github.com/chaijs/chai/issues/585 is resolved.

Based on the pace that things have been going lately, it's hard for me to imagine this getting any traction in core for the foreseeable future. Personally, I'd give a thumbs up to any effort to get `chai-things` compatible with the current Chai, but I don't have time for this myself.

**Comment by ethanresnick** [comment] 2018-02-10 23:09
> Based on the pace that things have been going lately, it's hard for me to imagine this getting any traction in core for the foreseeable future.

Ok, fair enough. I guess I'll just leave this issue as-is in case there's bandwidth to tackle it in the future or after #585 is resolved.

**Comment by silkentrance** [comment] 2018-04-30 22:28
@ethanresnick considering junit5's Assertions.assertAll() which takes an array of lamdas/callbacks, I would prefer something like

```
chai.assert.all(
  () => { chai.assert.equals(...) }.
  ... multiple assertions follow
);
```

the same goes for the other apis.

**Comment by keithamus** [comment] 2018-06-09 16:19
Hey @ethanresnick thanks for this issue!

This is an awesome idea! We're definitely going to be implimenting this for Chai 5 - but for now we'll close this, as there's going to be a bunch of work done for Chai 5, and so we've set up a project board for this. https://github.com/chaijs/chai/projects/2 is the roadmap board now. We'll be using that to track this feature.

Thanks for your input on chai!

**Closed by keithamus** 2018-06-09 16:19 UTC

**Comment by silkentrance** [comment] 2018-06-13 17:11
@keithamus I see that the AssertionError is factored out to the assertion-error package. Would you mind me stepping in and making this happen?

Basically I'd like to add a MultiAssertionError to that package which takes in multiple assertion errors and from that will render its final toString() or json representation.

As for the various interfaces, I would implement this as `all(callbacks)` on each interface separately, reusing common code where possible via `utils/multiassert`.

What do you think?

**Comment by silkentrance** [comment] 2018-06-13 17:44
@keithamus I am currently rethinking as `should` is an altogether different interface and it should not be added to that interface?

**Comment by silkentrance** [comment] 2018-06-13 17:51
@keithamus I am thinking whether this should be placed on the main chai export instead. This would allow users of also the `should` interface to use it without having to explicitly require chai.assert or chai.expect.
