### ISSUE TITLE
allow "is object" test with `oneOf`

### ISSUE THREAD

**Issue by nmschulte** [chaijs/chai#969] opened 2017-05-22 15:58 UTC
Currently there is no way to use `oneOf` to test the type of a value; it would be nice if `oneOf` allowed for testing that e.g. a value is "an object".

test:
```
  1) some function should return null or an object:
     AssertionError: expected {} to be one of [ null, {} ]
```

result:
```
describe('some function', () => {
    const someValue = someFunction();

     it('should return null or an object', () => {
        expect(someValue).to.be.oneOf([null, {}]);
    });
});
```

I also tried `expect(someValue).to.be.oneOf([null, Object.prototype])` (`Object.prototype` is an empty object, `{}`), with same results.

This concept generalizes to allow `oneOf` to assert a prototype/instance-of notion.  This would be _fantastic_ for "black-box" testing.

**Comment by keithamus** [comment] 2017-05-22 18:30
Hey @nmschulte thanks for the issue.

This looks a lot like a duplicate of https://github.com/chaijs/chai/issues/620. You should take a look at that for the discussion points around this. I'll quote one of our maintainers from that thread:

> I would strongly urge you to reconsider how you're structuring your tests rather than write a plugin for adding `or` functionality.
>
> If you find yourself needing `or` in your tests, it suggests one of two things:
> 1. **Your tests are non-deterministic**. In other words, each time you run your tests, you potentially get different results based on external conditions or pseudo-randomness. Rather than write tests that attempt to handle varying results by using `or`, I'd advise refactoring your tests, using test doubles as needed, in order to make your tests deterministic. The goal is for your tests to produce the exact same result each time they're run. And then, as keithamus exemplified in his first reply, a separate test should be written with different inputs (or different test doubles) in order to validate that the expected result is produced under each set of circumstances. Here's a pretty good resource on this topic: http://martinfowler.com/articles/nonDeterminism.html
> 2. **You're trying to reuse an assertion for multiple test cases**. I understand the allure of DRY, but a certain degree of repeating yourself is necessary when it comes to writing tests. In thomasvanlankveld's example, I'd recommend writing two completely separate tests, one that sets up the "post deleted" conditions, and then tests specifically that the desired outcome is produced, and then one that sets up the "post authorship changed" conditions, and then tests specifically that the desired outcome is produced. Even though both tests are testing identical outcomes, each test should be completely independent; they shouldn't reuse the same assertion, since that would require the assertion to be able to handle multiple scenarios with `or`.


I'll close this one, but thanks for filing this issue and please don't hesitate to open any new ones if you find anything new!

**Closed by keithamus** 2017-05-22 18:30 UTC

**Comment by nmschulte** [comment] 2017-05-22 19:15
> a separate test should be written with different inputs (or different test doubles) in order to validate that the expected result is produced under each set of circumstances

This seems reasonable; thanks.
