### ISSUE TITLE
Why does deep.contain assertion fail on these objects?

### ISSUE THREAD

**Issue by blah238** [chaijs/chai#399] opened 2015-03-11 21:29 UTC
I'm using `chai@1.10.0` (have also tested `chai@2.1.1` with same results), and getting the following error when running this assertion:

`expect(cache.permissions).to.deep.contain(_permission);`

```js
AssertionError: expected [ { users: [],
    roles:
     [ { name: 'test',
         createdAt: Wed Mar 11 2015 16:09:55 GMT-0500 (Central Daylight Time),
         updatedAt: Wed Mar 11 2015 16:09:55 GMT-0500 (Central Daylight Time),
         id: 1 } ],
    name: 'test',
    createdAt: Wed Mar 11 2015 16:09:55 GMT-0500 (Central Daylight Time),
    updatedAt: Wed Mar 11 2015 16:09:55 GMT-0500 (Central Daylight Time),
    id: 1,
    repository: undefined,
    task: undefined,
    dataset: undefined,
    permission: undefined } ] to include { users: [],
  roles:
   [ { name: 'test',
       createdAt: Wed Mar 11 2015 16:09:55 GMT-0500 (Central Daylight Time),
       updatedAt: Wed Mar 11 2015 16:09:55 GMT-0500 (Central Daylight Time),
       id: 1 } ],
  name: 'test',
  createdAt: Wed Mar 11 2015 16:09:55 GMT-0500 (Central Daylight Time),
  updatedAt: Wed Mar 11 2015 16:09:55 GMT-0500 (Central Daylight Time),
  id: 1,
  repository: undefined,
  task: undefined,
  dataset: undefined,
  permission: undefined }
```
This workaround works, however. Why? Something to do with dates?
`expect(JSON.parse(JSON.stringify(cache.permissions))).to.deep.contain(JSON.parse(JSON.stringify(_permission)));`

**Comment by keithamus** [comment] 2015-03-23 10:17
Hey @blah238 thanks for the issue.

This very much looks like a duplicate of #390. But if you can, would you kindly make a reduced test case? Try running `deep.equal` `deep.contain` and `deep.include` against various objects (some including dates, and some not), and let us know if you come up with any conclusions.

I'm going to close this on the assumption that its the same as #390, if you disagree feel free to explain why in a comment and I'll re-open it.

**Closed by keithamus** 2015-03-23 10:17 UTC
