### ISSUE TITLE
expect('test').to.have.lengthOf.above(2) throws Error

### ISSUE THREAD

**Issue by abimelex** [chaijs/chai#1033] opened 2017-08-24 09:37 UTC
Chaining lengthOf.above(N) does not work as expected. Also des example from the docs throws the following error:
`TypeError: expect(...).to.have.lengthOf.above is not a function`

Tested with string and array:
`expect([1, 2, 3]).to.have.lengthOf.above(2);`

Examples from here: http://chaijs.com/api/bdd/#method_above

**Comment by keithamus** [comment] 2017-08-24 11:12
Hey @abimelex thanks for the issue.

Seems to work fine for me: https://runkit.com/embed/h8fea13a73d8

Are you running the latest version of chai (4.1.1)?

I'll close this for now - as I'm unable to reproduce; but if you can provide us with a reproducible error then we'll re-open this and try to fix it!

**Closed by keithamus** 2017-08-24 11:12 UTC

**Comment by abimelex** [comment] 2017-08-24 12:17
ahw you'r right, I was still with version 3.5. Thank you!
