### ISSUE TITLE
Test passes when the thing after "to.be" is nonsense

### ISSUE THREAD

**Issue by hoegrammer** [chaijs/chai#549] opened 2015-11-09 09:50 UTC
```
describe('when writing tests using to.be', function() {
  it('passes when mispelled', function() {
    expect(true).to.be.flase;
  });
});
```

**Comment by hoegrammer** [comment] 2015-11-09 09:57
Actually it's not just after to.be. This also passes:

```
expect(true).footle;
```

Although this throws property-of-undefined:

```
expect(true).footle.bzzzzz;
```

**Comment by keithamus** [comment] 2015-11-09 10:06
Hi @hoegrammer, thanks for the issue.

This is a well known issue, and has been discussed a few times. If you want the history you can see #41, #297, #302, #306, #321, #326 and probably some others I've missed.

For ways we're actually planning to solve this problem, please have a look at our Roadmap in #457, and more specifically #407 - where we discuss adding proxies which would let us throw errors on undefined properties.

If you need a fix _right now_, then you have two options:

1. Don't use the property getters, instead use method alternatives, e.g. `expect(true).to.equal(false);`
2. Use [dirty-chai](https://www.npmjs.com/package/dirty-chai) which rewrites all of those property assertions to method assertions, so `expect(true).to.be.false` becomes `expect(true).to.be.false()`.

We'd love to get some help on making #407 a reality, so if you'd like to continue the discussion there, or perhaps make a pull request, that'd be awesome :smile: 

I'm closing this, given that it's a duplicate of all of the above mentioned issues.

**Closed by keithamus** 2015-11-09 10:06 UTC
