### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by ebacka** [chaijs/chai#1170] opened 2018-06-26 08:40 UTC
**And I want to test a property of a button in HTML using Chai  I  expect that this button to be disabled like this:**

` const chai = require('chai');
      const expect  = chai.expect;
     expect(document.getElementById('ref_button')).to.have.attr('disabled');`

**Wen including this line:**
`chai.use(require('chai-dom'))`

**I get this error:**

`Unhandled rejection ReferenceError: document is not defined
    at C:\Users\67563478\new_workspace\onconsup\node_modules\chai-dom\chai-dom.js:69:53
    at Object.exports.use (C:\Users\67563478\new_workspace\onconsup\node_modules\chai\lib\chai.js:39:5)
    at Object.<anonymous> (C:\Users\67563478\new_workspace\onconsup\e2e_cucumber\features\step_definitions\protocolo.js:16:6)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at C:\Users\67563478\new_workspace\onconsup\node_modules\cucumber\lib\cli\index.js:135:16
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (C:\Users\67563478\new_workspace\onconsup\node_modules\cucumber\lib\cli\index.js:134:24)
    at Cli.<anonymous> (C:\Users\67563478\new_workspace\onconsup\node_modules\cucumber\lib\cli\index.js:144:39)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Users\67563478\new_workspace\onconsup\node_modules\bluebird\js\release\util.js:16:23)`

**Comment by keithamus** [comment] 2018-06-26 17:18
Thanks for the issue @ebacka!

I think you'd have better luck perhaps reporting this issue on the [chai-dom issue tracker](https://github.com/nathanboktae/chai-dom/issues). The chai team doesn't manage `chai-dom` - which is a plugin.

Having said that, when you raise this with `chai-dom` I'd recommend also including the environment you're trying to run this on. It looks as though you might be trying to run these tests in Node.js - which does not have the DOM APIs by default. `chai-dom` only works in a browser, so if you want these to run in Node.js you'll have to also set up something like [`jsdom`](https://github.com/tmpvar/jsdom).

Unfortunately I won't be able to help you much further with this. I'll close this issue as it is not a bug within chai itself. Don't hesitate to file more issues when you find them though!

**Closed by keithamus** 2018-06-26 17:18 UTC

**Comment by ebacka** [comment] 2018-06-27 08:28
@keithamus  I do not understand what do you mean by running them in Node.js, cause I am using jsdom, but also I am runnng the tests in chrome not a headless browser.
