### ISSUE TITLE
Regression: deep properties and complex names

### ISSUE THREAD

**Issue by jlchereau** [chaijs/chai#434] opened 2015-04-27 20:23 UTC
[Mongoose](https://github.com/Automattic/mongoose) returns validation errors with complex property names like "version._versionId" herebelow:

```json
{
    "message": "Validation failed",
    "name": "ValidationError",
    "errors": {
        "version._versionId": {
            "message": "`version._versionId` is invalid: id `553e9924a1348128146217de` is not the latest published version for summary with id `553e9924a1348128146217da`.",
            "name": "ValidatorError",
            "path": "version._versionId",
            "type": "user defined",
            "value": "553e9924a1348128146217de"
        },
        "actor._userId": {
            "message": "`actor._userId` is invalid: id `553e9924a1348128146217d6` designates the author who is not allowed to create this type of activity.",
            "name": "ValidatorError",
            "path": "actor._userId",
            "type": "user defined",
            "value": "553e9924a1348128146217d6"
        }
    },
    "status": 400
}
```

In older versions of chai the following used to work:
```js
expect(res.body).to.have.deep.property('error.errors.version._versionId.name', 'ValidatorError');
```

and at some point:
```js
expect(res.body).to.have.deep.property('error.errors["version._versionId"].name', 'ValidatorError');
```

With version 2.3.0, neither works. Any workaround?

**Comment by jlchereau** [comment] 2015-04-28 07:22
Also, this does not work:

```js
expect(res.body).to.have.deep.property('error.originalError.errors').with.property('version._versionId');//.with.property('name', 'ValidatorError');
```

but this works:
```js
expect(res.body.error.originalError.errors).to.have.property('version._versionId').with.property('name', 'ValidatorError');
```

**Comment by jlchereau** [comment] 2015-04-28 07:47
I have rolled back all versions of Chai back to 2.0.0 and I cannot find any version when this worked. Please consider as a feature request.

**Comment by keithamus** [comment] 2015-04-29 09:13
Hey @jlchereau thanks for the issue.

The problem here is with the `.deep` flag and its use within `.property()`: When deep flag is enabled for an assertion, `.property()` will parse the given string as object notation, meaning chars like `.` and `[` get captured and parsed for traversal.

Because of this, an assertion like:

```js
expect(res.body).to.have.deep.property('error.originalError.errors.version._versionId');
```

Will not work because it expects the following:

```js
res['body']['error']['originalError']['errors']['version']['_versionId']
```

And of course that's not the object you have. Luckily, as of [Chai 2.2.0](https://github.com/chaijs/chai/releases/tag/2.2.0) you can escape these characters, and so this will work:

```js
// Note the escaping slashes:
expect(res.body).to.have.deep.property('error.originalError.errors.version\\._versionId');
```

Which expands to:

```js
res['body']['error']['originalError']['errors']['version._versionId']
```

Please let me know if this works for you. Also, I don't believe this to be a regression - but if you do could you please find the version to which we regressed? I'm going to close this because of the above reasoning, but please feel free to ask and I'll re-open, or raise a new issue.

**Closed by keithamus** 2015-04-29 09:13 UTC

**Comment by jlchereau** [comment] 2015-04-29 10:26
It works like a charm. Might be worth documenting on chaijs.com unless I missed it. Thank you not only for your help but also for a great test tool!

**Comment by keithamus** [comment] 2015-04-30 09:51
Apologies - the chaijs.com docs are slightly out of date. We're working on updating them to be more automatic in terms of site deployment because currently its a manual step.
