### ISSUE TITLE
WHATWG URL support

### ISSUE THREAD

**Issue by stevenvachon** [chaijs/chai#991] opened 2017-06-08 03:59 UTC
via [isurl](https://npmjs.com/isurl).

```js
expect(new URL('http://host/')).to.be.a('url');
```

**Comment by deltaidea** [comment] 2017-06-08 06:03
Isn't this good enough?

```JS
expect(new URL('http://host/')).to.be.an.instanceOf(URL)
```

**Comment by stevenvachon** [comment] 2017-06-08 15:34
What is `URL`: [whatwg-url](https://npmjs.com/whatwg-url), [`url.URL`](https://nodejs.org/api/url.html#url_the_whatwg_url_api), or [`window.URL`](https://developer.mozilla.org/en/docs/Web/API/URL)?

**Comment by shvaikalesh** [comment] 2017-06-08 15:45
Hey @stevenvachon, thanks for the issue.

However, I can't reproduce it with latest chai and Node. Are you using a shim?

**Comment by deltaidea** [comment] 2017-06-08 15:49
@stevenvachon `URL` is whatever you defined in your environment. `new URL` refers to the same thing. If you can do `new URL`, then you can certainly check if something is its instance.

**Comment by stevenvachon** [comment] 2017-06-08 15:54
@shvaikalesh There's nothing to reproduce as this is a feature request. I use [universal-url](https://npmjs.com/universal-url).

@deltaidea but being a standard object, I was hoping to get it built into chai.

**Comment by shvaikalesh** [comment] 2017-06-08 16:51
Snippet above works with latest chai and Node. If it doesn't, probably shim doesn't set `@@toStringTag`.

**Comment by stevenvachon** [comment] 2017-06-08 20:07
@shvaikalesh which snippet?

**Comment by keithamus** [comment] 2017-06-08 21:11
It looks as though [whatwg-url](https://www.npmjs.com/package/whatwg-url) (which is ultimately what [universal-url](https://npmjs.com/universal-url) uses) does not support `URL.prototype[Symbol.toStringTag]`, which value _should be_ `"URL"`. I would say this is the issue of whatwg-url missing that value, and not a problem with chai's code, which would support that value existing.

**Comment by keithamus** [comment] 2018-06-09 16:58
I think given the above description I am going to close this. This is an issue with whatwg-url. I dont think we can be reasonably expected to support this behaviour.

**Closed by keithamus** 2018-06-09 16:58 UTC
