### ISSUE TITLE
Update release log on https://www.chaijs.com/releases/

### ISSUE THREAD

**Issue by bugwelle** [chaijs/chai#1489] opened 2022-11-18 10:50 UTC
Hi,

could you update the release log on https://www.chaijs.com/releases/, please? :-)
The latest version there is 4.3.4, but chaijs on GitHub and npm is at 4.3.7.

Version 4.3.7 contains a possibly breaking change (see https://github.com/chaijs/chai/pull/1483#issuecomment-1319833148 ). I had to look into the commit history to see the relevant change.

Thank you very much for your continued work on chai.js. It's very much appreciated. 😄 

Kind regards,
Andre

**Comment by keithamus** [comment] 2022-11-18 12:19
Thanks for pointing this out. I think it's been broken for a long time :grimacing: (since September by the logs).

We used to use Travis to build the pages nightly, but it looks as though that's no longer operational. I've switched the setup GitHub Actions now, to build the pages, which seems to be working. 4.3.7 is listed in the released page. Hopefully we won't run into the same issue again.

I'll close this, as I feel the issue is resolved. Please don't hesitate to reach out again though, if you encounter this again.

**Closed by keithamus** 2022-11-18 12:19 UTC
