### ISSUE TITLE
Chaijs.com is parked/squatted/not serving-the-expected-bits

### ISSUE THREAD

**Issue by msiebuhr** [chaijs/chai#1193] opened 2018-09-12 11:20 UTC
Chaijs.com, the home of this project, is serving some kind of parking-page with a few ads:

![screen shot 2018-09-12 at 13 17 35](https://user-images.githubusercontent.com/330611/45421741-50158900-b68e-11e8-96e7-39f94ee1ce47.png)

In particular, all documentation links are dead-ends.

**Comment by keithamus** [comment] 2018-09-12 11:29
Hey @msiebuhr thanks for the issue

This seems to be a dupe of https://github.com/chaijs/chai/issues/1190 and https://github.com/chaijs/chaijs.github.io/issues/175. I'm really unsure of what is happening here, I'd like to find out if there is a comonality between you, @navneetgarg123 and @jbutz's internet connections that is causing this.

Here's what I get when I `dig chaijs.com`:

```bash
$ dig chaijs.com

; <<>> DiG 9.10.6 <<>> chaijs.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35270
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;chaijs.com.			IN	A

;; ANSWER SECTION:
chaijs.com.		2026	IN	A	192.30.252.153
chaijs.com.		2026	IN	A	192.30.252.154

;; Query time: 22 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Sep 12 12:28:08 BST 2018
;; MSG SIZE  rcvd: 80
```

Could you please run the same command and see what happens? Thanks

**Comment by meeber** [comment] 2018-09-12 11:54
@keithamus The chaijs website is working for me, and I get the same answer as you with nslookup and a normal dig, but I get a different answer with `+trace`:

```
dig chaijs.com +trace

; <<>> DiG 9.9.4-RedHat-9.9.4-61.amzn2.0.1 <<>> chaijs.com +trace
;; global options: +cmd
.                       82994   IN      NS      c.root-servers.net.
.                       82994   IN      NS      d.root-servers.net.
.                       82994   IN      NS      e.root-servers.net.
.                       82994   IN      NS      f.root-servers.net.
.                       82994   IN      NS      g.root-servers.net.
.                       82994   IN      NS      h.root-servers.net.
.                       82994   IN      NS      i.root-servers.net.
.                       82994   IN      NS      j.root-servers.net.
.                       82994   IN      NS      k.root-servers.net.
.                       82994   IN      NS      l.root-servers.net.
.                       82994   IN      NS      m.root-servers.net.
.                       82994   IN      NS      a.root-servers.net.
.                       82994   IN      NS      b.root-servers.net.
;; Received 228 bytes from 10.0.0.2#53(10.0.0.2) in 17 ms

com.                    172800  IN      NS      f.gtld-servers.net.
com.                    172800  IN      NS      b.gtld-servers.net.
com.                    172800  IN      NS      d.gtld-servers.net.
com.                    172800  IN      NS      h.gtld-servers.net.
com.                    172800  IN      NS      i.gtld-servers.net.
com.                    172800  IN      NS      a.gtld-servers.net.
com.                    172800  IN      NS      k.gtld-servers.net.
com.                    172800  IN      NS      m.gtld-servers.net.
com.                    172800  IN      NS      j.gtld-servers.net.
com.                    172800  IN      NS      c.gtld-servers.net.
com.                    172800  IN      NS      e.gtld-servers.net.
com.                    172800  IN      NS      g.gtld-servers.net.
com.                    172800  IN      NS      l.gtld-servers.net.
com.                    86400   IN      DS      30909 8 2 E2D3C916F6DEEAC73294E82                                          68FB5885044A833FC5459588F4A9184CF C41A5766
com.                    86400   IN      RRSIG   DS 8 1 86400 20180925050000 20180                                          912040000 41656 . GTPpQ8IK0eaW0YZ6TyMBpi/OsYat4p9hO30o9x38Bmt5CD5wNuI4/rjc 2RVB3K                                          FcvzcaaBMqtdNHd1ZquZ0S13S294xiQqbbGSpmfMQoeDHl+5jn i+yrClm+t06lKWoCmSuUg03pXJwuPc                                          V0Zr5zASF+rSLydpgviwpDGiK3 1xWqQH5eS8G6zQd+9bqjiaENML5D4qd1oQHNSyDvdHY8o1HuPJu/sq                                          Gw AmSrhuZ1YG1Xn/MOvKhtYDfJ4ilcBbeiiqQn+LtUhrReh1h6FKttVoUj uYQg+YpIn/0jNnQzX7UCq                                          8Sf2aFQLjENdo3FHTgAID74DrCqVQfRbrsk fMc/LA==
;; Received 1170 bytes from 192.36.148.17#53(i.root-servers.net) in 14 ms

chaijs.com.             172800  IN      NS      ns1is.alogicalparadox.com.
chaijs.com.             172800  IN      NS      ns2is.alogicalparadox.com.
chaijs.com.             172800  IN      NS      ns3is.alogicalparadox.com.
chaijs.com.             172800  IN      NS      ns4is.alogicalparadox.com.
CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN NSEC3 1 1 0 - CK0Q1GIN43N1ARRC9OSM                                          6QPQR81H5M9A NS SOA RRSIG DNSKEY NSEC3PARAM
CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN RRSIG NSEC3 8 2 86400 201809170443                                          05 20180910033305 46475 com. T/foftH+GS7seSLRzFFjOHxRxNr40SO7l74hELDmGOanjRcs3f75                                          /BqM BCZi7aZ2A8qrAqnurzgsyGIiwbfDWmu3lvVaH+3HFlMkjYXv3t2niveT pSS2fDqIRgvzOGT3SIa                                          BdELgdCBwGPXpPKNfxtDrfH8nfip1pL9nKv0s uaI=
AJPOMNVKIC1Q27CG781S3LMARETVRVCQ.com. 86400 IN NSEC3 1 1 0 - AJPTP1D3JPHIQ4EJ9QLN                                          7QC8GMG232G3 NS DS RRSIG
AJPOMNVKIC1Q27CG781S3LMARETVRVCQ.com. 86400 IN RRSIG NSEC3 8 2 86400 201809180502                                          35 20180911035235 46475 com. qswy5tWOha6TRUUb9bgCWKifO7zMNVTNMFzZJDxNmg8kRjDJFwxj                                          R5Q7 jhb4cZINRYEolqtACJ6zPcVZK/57WC4BthZ/bN3agEGoZL8IUR1k3b82 4E+bb5TvyOgNB0pPI95                                          KfFYZicks5j1ePe0BMGakY2++rTtGRweBere4 THI=
;; Received 860 bytes from 192.41.162.30#53(l.gtld-servers.net) in 322 ms

chaijs.com.             300     IN      A       209.99.40.222
;; Received 55 bytes from 209.99.40.222#53(ns3is.alogicalparadox.com) in 35 ms
```

**Comment by meeber** [comment] 2018-09-12 12:16
I suspect the problem is with the `ns[1-4]is.alogicalparadox.com` name servers.

**Comment by msiebuhr** [comment] 2018-09-12 12:51
Yup. Your DNS provider looks problematic:

Running `dig chaijs.com +trace` mostly gives this:

```
; <<>> DiG 9.8.3-P1 <<>> chaijs.com +trace
;; global options: +cmd
.			80767	IN	NS	i.root-servers.net.
.			80767	IN	NS	d.root-servers.net.
.			80767	IN	NS	a.root-servers.net.
.			80767	IN	NS	m.root-servers.net.
.			80767	IN	NS	e.root-servers.net.
.			80767	IN	NS	k.root-servers.net.
.			80767	IN	NS	c.root-servers.net.
.			80767	IN	NS	b.root-servers.net.
.			80767	IN	NS	j.root-servers.net.
.			80767	IN	NS	h.root-servers.net.
.			80767	IN	NS	l.root-servers.net.
.			80767	IN	NS	g.root-servers.net.
.			80767	IN	NS	f.root-servers.net.
;; Received 241 bytes from 192.168.2.1#53(192.168.2.1) in 14 ms

com.			172800	IN	NS	a.gtld-servers.net.
com.			172800	IN	NS	b.gtld-servers.net.
com.			172800	IN	NS	c.gtld-servers.net.
com.			172800	IN	NS	d.gtld-servers.net.
com.			172800	IN	NS	e.gtld-servers.net.
com.			172800	IN	NS	f.gtld-servers.net.
com.			172800	IN	NS	g.gtld-servers.net.
com.			172800	IN	NS	h.gtld-servers.net.
com.			172800	IN	NS	i.gtld-servers.net.
com.			172800	IN	NS	j.gtld-servers.net.
com.			172800	IN	NS	k.gtld-servers.net.
com.			172800	IN	NS	l.gtld-servers.net.
com.			172800	IN	NS	m.gtld-servers.net.
;; Received 488 bytes from 192.58.128.30#53(192.58.128.30) in 34 ms

chaijs.com.		172800	IN	NS	ns1is.alogicalparadox.com.
chaijs.com.		172800	IN	NS	ns2is.alogicalparadox.com.
chaijs.com.		172800	IN	NS	ns3is.alogicalparadox.com.
chaijs.com.		172800	IN	NS	ns4is.alogicalparadox.com.
;; Received 364 bytes from 192.43.172.30#53(192.43.172.30) in 23 ms

chaijs.com.		7200	IN	A	192.30.252.154
chaijs.com.		7200	IN	A	192.30.252.153
;; Received 60 bytes from 162.251.82.251#53(162.251.82.251) in 137 ms
```

But every now and then, I get:
```
; <<>> DiG 9.8.3-P1 <<>> chaijs.com +trace
;; global options: +cmd
.			80765	IN	NS	d.root-servers.net.
.			80765	IN	NS	l.root-servers.net.
.			80765	IN	NS	c.root-servers.net.
.			80765	IN	NS	j.root-servers.net.
.			80765	IN	NS	e.root-servers.net.
.			80765	IN	NS	i.root-servers.net.
.			80765	IN	NS	m.root-servers.net.
.			80765	IN	NS	h.root-servers.net.
.			80765	IN	NS	b.root-servers.net.
.			80765	IN	NS	k.root-servers.net.
.			80765	IN	NS	f.root-servers.net.
.			80765	IN	NS	a.root-servers.net.
.			80765	IN	NS	g.root-servers.net.
;; Received 241 bytes from 192.168.2.1#53(192.168.2.1) in 51 ms

com.			172800	IN	NS	l.gtld-servers.net.
com.			172800	IN	NS	i.gtld-servers.net.
com.			172800	IN	NS	d.gtld-servers.net.
com.			172800	IN	NS	a.gtld-servers.net.
com.			172800	IN	NS	e.gtld-servers.net.
com.			172800	IN	NS	j.gtld-servers.net.
com.			172800	IN	NS	f.gtld-servers.net.
com.			172800	IN	NS	m.gtld-servers.net.
com.			172800	IN	NS	k.gtld-servers.net.
com.			172800	IN	NS	b.gtld-servers.net.
com.			172800	IN	NS	h.gtld-servers.net.
com.			172800	IN	NS	g.gtld-servers.net.
com.			172800	IN	NS	c.gtld-servers.net.
;; Received 488 bytes from 193.0.14.129#53(193.0.14.129) in 63 ms

chaijs.com.		172800	IN	NS	ns1is.alogicalparadox.com.
chaijs.com.		172800	IN	NS	ns2is.alogicalparadox.com.
chaijs.com.		172800	IN	NS	ns3is.alogicalparadox.com.
chaijs.com.		172800	IN	NS	ns4is.alogicalparadox.com.
;; Received 364 bytes from 192.54.112.30#53(192.54.112.30) in 63 ms

chaijs.com.		300	IN	A	209.99.40.223
;; Received 44 bytes from 209.99.40.222#53(209.99.40.222) in 146 ms
```

**Comment by keithamus** [comment] 2018-09-12 13:06
Well, it seems as though @logicalparadox's `alogicalparadox.com.` domain - for which the nameservers are pointing to - has expired, and this is the problem.

```js
whois alogicalparadox.com |grep Expir
Registry Expiry Date: 2019-09-06T18:02:06Z
Registrar Registration Expiration Date: 2018-09-06T18:02:06Z
Registrar Registration Expiration Date: 2018-09-06T18:02:06Z
```

This is quite problematic. I've tried emailing @logicalparadox so we can get the DNS shifted over, but the email bounced.

At this point I'm kind of unsure what to do...

**Comment by jbutz** [comment] 2018-09-12 13:19
If you still need dig output, here is mine. The site is currently working for me.

```
$ dig chaijs.com

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> chaijs.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34542
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;chaijs.com.                    IN      A

;; ANSWER SECTION:
chaijs.com.             7200    IN      A       192.30.252.153
chaijs.com.             7200    IN      A       192.30.252.154

;; Query time: 154 msec
;; SERVER: 208.67.220.220#53(208.67.220.220)
;; WHEN: Wed Sep 12 09:17:57 DST 2018
;; MSG SIZE  rcvd: 71

$ dig chaijs.com +trace

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> chaijs.com +trace
;; global options: +cmd
.                       518400  IN      NS      a.root-servers.net.
.                       518400  IN      NS      b.root-servers.net.
.                       518400  IN      NS      c.root-servers.net.
.                       518400  IN      NS      d.root-servers.net.
.                       518400  IN      NS      e.root-servers.net.
.                       518400  IN      NS      f.root-servers.net.
.                       518400  IN      NS      g.root-servers.net.
.                       518400  IN      NS      h.root-servers.net.
.                       518400  IN      NS      i.root-servers.net.
.                       518400  IN      NS      j.root-servers.net.
.                       518400  IN      NS      k.root-servers.net.
.                       518400  IN      NS      l.root-servers.net.
.                       518400  IN      NS      m.root-servers.net.
;; Received 239 bytes from 208.67.220.220#53(208.67.220.220) in 9 ms

com.                    172800  IN      NS      a.gtld-servers.net.
com.                    172800  IN      NS      b.gtld-servers.net.
com.                    172800  IN      NS      c.gtld-servers.net.
com.                    172800  IN      NS      d.gtld-servers.net.
com.                    172800  IN      NS      e.gtld-servers.net.
com.                    172800  IN      NS      f.gtld-servers.net.
com.                    172800  IN      NS      g.gtld-servers.net.
com.                    172800  IN      NS      h.gtld-servers.net.
com.                    172800  IN      NS      i.gtld-servers.net.
com.                    172800  IN      NS      j.gtld-servers.net.
com.                    172800  IN      NS      k.gtld-servers.net.
com.                    172800  IN      NS      l.gtld-servers.net.
com.                    172800  IN      NS      m.gtld-servers.net.
com.                    86400   IN      DS      30909 8 2 E2D3C916F6DEEAC73294E8268FB5885044A833FC5459588F4A9184CF C41A5766
com.                    86400   IN      RRSIG   DS 8 1 86400 20180925050000 20180912040000 41656 . GTPpQ8IK0eaW0YZ6TyMBpi/OsYat4p9hO30o9x38Bmt5CD5wNuI4/rjc 2RVB3KFcvzcaaBMqtdNHd1ZquZ0S13S294xiQqbbGSpmfMQoeDHl+5jn i+yrClm+t06lKWoCmSuUg03pXJwuPcV0Zr5zASF+rSLydpgviwpDGiK3 1xWqQH5eS8G6zQd+9bqjiaENML5D4qd1oQHNSyDvdHY8o1HuPJu/sqGw AmSrhuZ1YG1Xn/MOvKhtYDfJ4ilcBbeiiqQn+LtUhrReh1h6FKttVoUj uYQg+YpIn/0jNnQzX7UCq8Sf2aFQLjENdo3FHTgAID74DrCqVQfRbrsk fMc/LA==
;; Received 1170 bytes from 199.7.83.42#53(l.root-servers.net) in 14 ms

chaijs.com.             172800  IN      NS      ns1is.alogicalparadox.com.
chaijs.com.             172800  IN      NS      ns2is.alogicalparadox.com.
chaijs.com.             172800  IN      NS      ns3is.alogicalparadox.com.
chaijs.com.             172800  IN      NS      ns4is.alogicalparadox.com.
CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN NSEC3 1 1 0 - CK0Q1GIN43N1ARRC9OSM6QPQR81H5M9A  NS SOA RRSIG DNSKEY NSEC3PARAM
CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN RRSIG NSEC3 8 2 86400 20180917044305 20180910033305 46475 com. T/foftH+GS7seSLRzFFjOHxRxNr40SO7l74hELDmGOanjRcs3f75/BqM BCZi7aZ2A8qrAqnurzgsyGIiwbfDWmu3lvVaH+3HFlMkjYXv3t2niveT pSS2fDqIRgvzOGT3SIaBdELgdCBwGPXpPKNfxtDrfH8nfip1pL9nKv0s uaI=
AJPOMNVKIC1Q27CG781S3LMARETVRVCQ.com. 86400 IN NSEC3 1 1 0 - AJPTP1D3JPHIQ4EJ9QLN7QC8GMG232G3  NS DS RRSIG
AJPOMNVKIC1Q27CG781S3LMARETVRVCQ.com. 86400 IN RRSIG NSEC3 8 2 86400 20180918050235 20180911035235 46475 com. qswy5tWOha6TRUUb9bgCWKifO7zMNVTNMFzZJDxNmg8kRjDJFwxjR5Q7 jhb4cZINRYEolqtACJ6zPcVZK/57WC4BthZ/bN3agEGoZL8IUR1k3b82 4E+bb5TvyOgNB0pPI95KfFYZicks5j1ePe0BMGakY2++rTtGRweBere4 THI=
;; Received 860 bytes from 192.12.94.30#53(e.gtld-servers.net) in 27 ms

chaijs.com.             300     IN      A       209.99.40.223
;; Received 55 bytes from 209.99.40.223#53(ns4is.alogicalparadox.com) in 42 ms
```

**Comment by navneetgarg123** [comment] 2018-09-12 14:49
@keithamus 
Confirmed at least on my home and cellular network I don’t have this issue. 
It seems to happen only at the office, which is awesome.

```
; <<>> DiG 9.10.6 <<>> chaijs.com +trace
;; global options: +cmd
.			40365	IN	NS	h.root-servers.net.
.			40365	IN	NS	g.root-servers.net.
.			40365	IN	NS	d.root-servers.net.
.			40365	IN	NS	f.root-servers.net.
.			40365	IN	NS	j.root-servers.net.
.			40365	IN	NS	m.root-servers.net.
.			40365	IN	NS	e.root-servers.net.
.			40365	IN	NS	i.root-servers.net.
.			40365	IN	NS	c.root-servers.net.
.			40365	IN	NS	b.root-servers.net.
.			40365	IN	NS	a.root-servers.net.
.			40365	IN	NS	l.root-servers.net.
.			40365	IN	NS	k.root-servers.net.

;; Received 1097 bytes from 172.23.16.10#53(172.23.16.10) in 49 ms

com.			172800	IN	NS	k.gtld-servers.net.
com.			172800	IN	NS	i.gtld-servers.net.
com.			172800	IN	NS	g.gtld-servers.net.
com.			172800	IN	NS	b.gtld-servers.net.
com.			172800	IN	NS	d.gtld-servers.net.
com.			172800	IN	NS	c.gtld-servers.net.
com.			172800	IN	NS	j.gtld-servers.net.
com.			172800	IN	NS	a.gtld-servers.net.
com.			172800	IN	NS	l.gtld-servers.net.
com.			172800	IN	NS	e.gtld-servers.net.
com.			172800	IN	NS	h.gtld-servers.net.
com.			172800	IN	NS	m.gtld-servers.net.
com.			172800	IN	NS	f.gtld-servers.net.

;; Received 1170 bytes from 192.36.148.17#53(i.root-servers.net) in 53 ms

chaijs.com.		172800	IN	NS	ns1is.alogicalparadox.com.
chaijs.com.		172800	IN	NS	ns2is.alogicalparadox.com.
chaijs.com.		172800	IN	NS	ns3is.alogicalparadox.com.
chaijs.com.		172800	IN	NS	ns4is.alogicalparadox.com.

;; Received 860 bytes from 192.43.172.30#53(i.gtld-servers.net) in 49 ms

chaijs.com.		300	IN	A	209.99.40.222
;; Received 55 bytes from 209.99.40.222#53(ns3is.alogicalparadox.com) in 33 ms
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by keithamus** [comment] 2018-09-12 15:06
Sorry to everyone experiencing this. I'm not sure there is much we can do - sadly. I'll keep trying to get in contact with @logicalparadox to get the NS records changed so we don't lose the site. If anyone has any other ideas please share 😄

**Comment by msiebuhr** [comment] 2018-09-13 06:09
You could look into hosting at https://js.org. The domain won't be far off `chai.js.org` vs. `chaijs.com` and it looks like someone is already taking care of infrastructure...

**Comment by keithamus** [comment] 2018-09-14 22:36
I'll close this now. The DNS is under my control in my cloudflare account.

**Closed by keithamus** 2018-09-14 22:36 UTC
