### ISSUE TITLE
__proto__ causes mostly identical objects to fail under assert.deepEqual when the object was created via a constructor versus hard coded.

### ISSUE THREAD

**Issue by josephmcasey** [chaijs/chai#518] opened 2015-09-15 16:32 UTC
it('Test', function(){
        var arg1 = {id: 1, name:'GA1',key:'GB1'};
        var arg2 = {id: 1, name:'TA1',key:'TB1'};
        var arg3 = true;
        var input = //Function that uses the prototype chain to create a efficiently utilize the distribution of methods via a class object.
        var expected = {id: 1, name:'TA1',key:'TB1'};
        assert.deepPropertyVal(input,expected);
    })

---------------------------------

input = {id: 1, name:'TA1',key:'TB1'};
expected = {id: 1, name:'TA1',key:'TB1'};

------------------------------

  2) Test Functionality of Content:  Test:

      Read rows of generator.
      + expected - actual

      
      at Assertion.assertEql (node_modules/Chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/Chai/lib/chai/utils/addMethod.js:40:25)
      at Function.assert.deepEqual (node_modules/Chai/lib/chai/interface/assert.js:205:32)
      at Context.<anonymous> (test/index.js:582:16)

---------------------------------

Input = __proto__ = VenueContentRow
Expected = __proto__ = Object

----------------------------------

Just to be clear, this is working as intended and it is not a bug. Most likely this is just a very particular use case for which documentation is difficult to find.

It would be convenient if a simple argument could be added to ignore this and only compare the properties except the prototype chain.

**Comment by josephmcasey** [comment] 2015-09-15 16:38
If it helps. I am currently writing my tests to utilize

    assert.deepPropertyVal(input, 'name', 'nameValue');

It is just a little pedantic

**Comment by keithamus** [comment] 2015-09-21 10:03
Hey @josephmcasey thanks for the issue.

I think this is working as intended. If two objects have different prototypes, then they're different objects and aren't equal, nor deeply equal.

The simplest way to test these, as you say, is using `deepPropertyVal`. We discussed having `.properties` assertion in #72 but it didn't go very far.

I'll close this issue, as this is intended behaviour. If you'd like to discuss it further though, feel free to do so :smile:

**Closed by keithamus** 2015-09-21 10:03 UTC
