### ISSUE TITLE
Documentation site has expired 

### ISSUE THREAD

**Issue by navneetgarg123** [chaijs/chai#1190] opened 2018-09-10 22:43 UTC
The docs site currently says the “domain name has expired on 2019-12-16 08:51:55”

Is this project/site maintained anymore?

**Comment by keithamus** [comment] 2018-09-10 23:49
Hey @navneetgarg123 thanks for the issue.

This looks to be a dupe of https://github.com/chaijs/chaijs.github.io/issues/175

I don't know how you're getting that error. By my calculations it is not `2019-12-16` (unless my time machine didn't take me back far enough, but I make it `2018-09-11`). The domain is still under our control for at least another year. 

My guess is whatever internet connection you're using is somehow hijacking the DNS of chaijs.com. I'd recommend taking this up with your ISP

**Closed by keithamus** 2018-09-10 23:49 UTC
