### ISSUE TITLE
Request:  smoother Chai as Arguments validator

### ISSUE THREAD

**Issue by gregglind** [chaijs/chai#346] opened 2015-01-20 20:38 UTC
(if this already exists, please point me to where.  My search skills failed here)

**Use case**:  guards / validators  in function arguments

1.  Chai is already a DSL for describing data and state.
2.  I am already using it on the test / backend to check input.

**Wants**:
1.  Easy way to `uncall` an expect statement
2.  Nicer way to control exception vs. false-ness
3.  Better thinking / design than my silly implemention (following)

**Example implementation (which feels gross!)**
```js
/* return [Errors, isOk] for a config, with some rules. */
var rules = [
    function (c) {chai.expect(c.name).to.be.a("string")},
    function (c) {chai.expect(c.description).to.be.a("string")},
    function (c) {chai.expect(c.recipe).to.be.a("function")},
    function (c) {chai.expect(c.shouldRun).to.be.a("function")}
]
let validateConfig = function (config, rules) {
  var errors  = [];
  rules.map(function(rule) {
    try {
      rule(config)}
    catch (E) {
      errors.push(E);
    }
  });
  return ([errors, errors.length == 0])
}; 

validateConfig({name:"a", rules})   // =>  [3 errors, false] 
```
**Alternative ideas**
- rules could also be a dict
- return value has different arity.

**Comment by keithamus** [comment] 2015-01-21 17:08
Thanks for the issue @gregglind. Could I get a little bit more about your usecase for using Chai. Unless I'm mistaken, it seems like you're using Chai outside of test code. If so I wouldn't recommend it.

**Comment by gregglind** [comment] 2015-01-21 17:48
@keithamus, I *am* suggesting it has use outside test code.  I am curious about why recommend against it?  If I have to describe structures for tests, it seems convenient to validate using that same library.  I am trying to avoid validating objects different ways at different layers.  

Chai is a 'big' (5000 LOC) library.  That's the only reason I have not to use it.  Tell me others.

(if you have a good validation library to recommend, please share it!)

**Comment by keithamus** [comment] 2015-01-22 12:41
Well, chai's primary focus is around testing - and so it doesn't focus on what is important in a frontend or backend library that is production ready. To expand on this, chai's concerns are:

- Compatibility with test runners (which means throwing errors instead of returning values
- Lots of Assertions for testing behaviours of functions and exact equality (so things like `.eql`, `.deep.equal`, `.throws` and `.satisfy` none of which you'll need)
- Easy to use DSL, specifically for use within a test environment (e.g. `.should` which modifies Object.prototype - which typically is a big nono in real code)

Things we're not concerned about:

- Compatibility with really old browsers (we don't support IE<9)
- Code size (as you mention, its 5k LOC, 121k unminified, we never package a minified version because there is no point.
- Memory usage (I'm not saying Chai is bad at memory usage or has memory leaks, but we don't go out of our way to check for these at it executes in a short lived environment).

For a validation library, the concerns have very little overlap with what Chai does:
 - It would not be concerned with explicit values, more regex/typeof style checks.
 - It would probably care about code size and browser compat, especially as an FE tool.
 - It would definitely be concerned about performance including memory & speed
  -  Try/Catching errors is actually much slower than regular control flow statements. A validation library would probably just return true/false or maybe an error message.

So in summary, using chai for this means a lot of overhead in terms of speed, code size & compatibility, for what is a nice DSL. You _could use_ chai for this, but its not the best tool for the job.

Just given your code example, it could be reduced to this, without using chai:

```js
function typeCheck(prop, type) {
    if (typeof prop !== type) return new Error('expected ' + prop + ' to be ' + type + ' but got ' + typeof prop);
}
var rules = [
    function (c) { return typeCheck(c.name, 'string') },
    function (c) { return typeCheck(c.description, 'string'); },
    function (c) { return typeCheck(c.recipe, 'function'); },
    function (c) { return typeCheck(c.shouldRun, 'function'); }
];
function validate(config, rules) {
   var errors = rules.map(function (rule) { return rule(config); }).filter(function (e) { return e; });
   return [errors, errors.length === 0];
}
validate(config, rules); // =>  [3 errors, false] 
```

**Comment by joshperry** [comment] 2015-01-25 21:26
This  feels like a fancy regression to returning and checking error codes. We have exceptions, they're meant for flow control in the face of exceptional circumstances.

In async code, exceptions can still be thrown but we receive these errors in a CPS function argument (`if(err){...}` should have first-class language support in node); because of this, it can frequently feel like exceptions and async code are completely incompatible. This is a little better with promises as you can have one error handler at the end of a chain of async processing and is nearly identical, in form and function, to try/catch.

Most programs have two types of errors, implementor errors, and environment errors. In this case, what you're obviously trying to catch are implementor errors, failing quickly and synchronously is your best bet for things like precondition checking.

While the code you're proposing looks nice and succinct for checking for type errors and passing those back to the call-site, what you've neglected to show is the calling code. The most likely use-case is that you want to convey the error to the caller so that they can fix their code. How is a user at runtime going to change the type of an object property?

Take a look at how this lib [xbee-promise](https://github.com/prodatakey/xbee-promise/blob/master/lib/xbee-promise.js#L326), that I've made some contributions to, handles input checking. It uses a library called parambulator that does something similar to what you want. I'll be working to remove this library from the code because it quickly devolves into a complex mess of parambulator DSL and tertiary validation functions. 

Never underestimate the simplicity and efficacy of `assert()`;

**Comment by keithamus** [comment] 2015-02-23 21:14
For now @gregglind, I'm going to close this issue. I think you've sparked something interesting here though. I'm definitely going to put some thought into how Chai can evolve over the next few versions to be able to cater to use cases like these.

**Closed by keithamus** 2015-02-23 21:14 UTC

**Comment by gregglind** [comment] 2015-02-23 21:22
I think that is wise!  I have been looking over other contracts and args validation libraries.  

Including chai at runtime adds a lot of bulk, for reasons that aren't entirely clear.  

I know that I am sick of writing 'hasKeys()' over and over though, and want something a little beefier than 'isType'!

**Comment by SPSpwetter** [comment] 2016-08-16 21:09
chai-param does something like what you want. https://github.com/theblacksmith/chai-param So does "assumejs": https://www.npmjs.com/package/assumejs
