### ISSUE TITLE
expect.throw do not always works (provided script)

### ISSUE THREAD

**Issue by Alex-Werner** [chaijs/chai#1268] opened 2019-07-05 07:45 UTC
Chai version `^4.2.0`

**Example Code:**
```
 const method = () => {
      throw new Error('Wallet is not loaded.');
    };

    const expectedException1 = 'd'
    expect(() => method()).to.throw(expectedException1);
```

**Expected Result**
It should throw error with ` AssertionError: expected [Function] to throw error including 'd' but got 'Wallet is not loaded.'`

**Real Result**
It passes. 

**Notes :**
This is a funny one, if error is `'Wallet is not loa'` (lenght: 17 char), then it works correctly. 
Let put back to Wallet is not loaded. as an error, but change `expectedException1` from `d` to `dd`, then it works also. 

This is an isolated small cases, obviously I don't expect `d` as an error, but I think it actually happened on a more `real` case once which was an issue.

**Comment by fizker** [comment] 2019-08-07 10:03
I think this is a classic case of RTM. From https://www.chaijs.com/api/bdd/#method_throw:

> When one argument is provided, and it’s a string, .throw invokes the target function and asserts that an error is thrown with a message that contains that string.
```
var badFn = function () { throw new TypeError('Illegal salmon!'); };

expect(badFn).to.throw('salmon');
```

What you want for your case is `expect(() => method()).to.throw(/^d$/)`, so that it matches that exact string

**Comment by keithamus** [comment] 2019-08-19 13:51
Hey @Alex-Werner thanks for the issue.

As @fizker has pointed out, this is a "Feature Not a Bug" 😉.  The string argument checks for inclusion not equality.

I'll close this issue, as it's the intended behaviour and documented as such. Feel free to continue the discussion though, if you think this is wrong and we should change it then we can always re-open the issue!

**Closed by keithamus** 2019-08-19 13:51 UTC
