### ISSUE TITLE
to.have.property not detects undefined fields

### ISSUE THREAD

**Issue by blacksonic** [chaijs/chai#380] opened 2015-02-27 09:49 UTC
The property matcher behaves not consistently for undefined values
```
var obj = { x: undefined, y: 1}
expect(obj).to.have.property('x') // not pass
```
but checking like this:
```
expect(Object.getOwnPropertyNames(obj)).to.contain('x') // pass
```

**Comment by keithamus** [comment] 2015-02-27 12:23
Hey @blacksonic thanks for the issue.

This issue is actually a duplicate of #184 - which was fixed in [Chai 2.0.0](https://github.com/chaijs/chai/releases/tag/v2.0.0). It was fixed in PR #308 if you're curious.

Here's a code sample of it working in Chai 2.0.0:
```js
> var obj = { x: undefined, y: 1}
undefined
> expect(obj).to.have.property('x')
{ __flags: { ssfi: [Function], object: undefined, message: undefined } }
```

Also, if you need the behaviour to work for older version of chai, you can opt to use the `ownProperty` assertion instead, I believe.

```js
expect(obj).to.have.ownProperty('x')
```
`ownProperty` doesn't pass the property value over though, so you cannot chain it in the same way.

I'm going to close this issue - because of the above. If you still feel it is a problem, let me know and I'll reopen it :smile:

**Closed by keithamus** 2015-02-27 12:23 UTC

**Comment by blacksonic** [comment] 2015-02-27 12:58
thanks, upgrading to new version solved the issue

**Comment by lpender** [comment] 2016-02-17 00:03
I'm on `3.4.1` and having this issue.

```
console.log(data[key]); // "undefined"
expect(data).to.have.property(key); // pass
```
