### ISSUE TITLE
Testing all objects in an array

### ISSUE THREAD

**Issue by MohamadAtieh** [chaijs/chai#410] opened 2015-03-26 15:35 UTC
I am having trouble testing all objects in my list. I can validate one object but what if I want to test all objects the same way given an array in the response?

I went over the API, it can test an element based on a given index(es). How can I iterate through them all and check if a key exists in each for example? 

Link:
https://github.com/MohamadAtieh/node-endpoint/blob/master/test/common/validate.js#L54

**Comment by adrianblynch** [comment] 2015-03-26 15:48
Loop over the array and test each item in order? Not a Chai solution but should work.

**Comment by keithamus** [comment] 2015-03-26 16:00
@MohamadAtieh thanks for the issue!

To help me here, could you tell me what kind of API you'd expect Chai to have to do this. Give me a concrete example of what you'd like to do in Chai. 

From the look of your tests I would suggest you have a look at [chai-json-schema](https://www.npmjs.com/package/chai-json-schema) which would probably replace a lot of the tests you have.

**Comment by MohamadAtieh** [comment] 2015-03-26 16:59
Thanks for the response @keithamus, I will definitely check out the plugin, it might solve my issue as well.

something like: `expect(foo).to.have.all.deep.keys('bar', 'baz');` where `foo` is an array, and the keys exist in every document.

**Comment by MohamadAtieh** [comment] 2015-03-26 17:00
@adrianblynch I have thought about that, but what if the list was long?

**Comment by keithamus** [comment] 2015-03-26 17:43
@MohamadAtieh you may also like to have a look at [chai-things](https://www.npmjs.com/package/chai-things) which does almost exactly what you want:

```js
// All items have a property 'a'
[{ a: 'cat' }, { a: 'dog' }].should.all.have.property('a')

[{ a: 'cat' }, { a: 'dog' }].should.all.have.property('a', 'cat')
/* expected all elements of [ { a: 'cat' }, { a: 'dog' } ] to have a property 'a' of 'cat', but got 'dog' */
```

Given the recommendations of both [chai-things](https://www.npmjs.com/package/chai-things) and [chai-json-schema](https://www.npmjs.com/package/chai-json-schema) - I'm going to close this issue as I feel those plugins will have you covered. If you still aren't satisfied with those, feel free to raise a new issue, or comment here and I'll re-open this one.

**Closed by keithamus** 2015-03-26 17:43 UTC

**Comment by MohamadAtieh** [comment] 2015-03-30 15:42
Thanks @keithamus!

**Comment by KamilOcean** [comment] 2017-11-16 15:56
Short solution in one line with ES6 arrow functions, that i always use

```js
yourArray.every(i => expect(i).to.have.all.keys('bar', 'baz'))
```

By the way `Array.prototype.every` is ES5.1

**Comment by chtseac** [comment] 2017-12-03 09:20
@KamilOcean Using `Array.prototype.every` relies on `Assertion` being truthy. Although it always is, this usage would easily lead to unexpected behaviors like these:

    // bad!
    bars.every(bar => {
        if (bar.isVisible()){
            expect(bar).to.satisfy(bar => bar.isHorizontal())
        }
    })

Since the outer arrow function does not return anything (returns `undefined`), only the first `bar` value is checked!

I suggest using `Array.prototype.forEach` instead, which does not check if the return values are true or not and terminates early.
