### ISSUE TITLE
expect.fail() and should.fail() are not documented

### ISSUE THREAD

**Issue by astorije** [chaijs/chai#487] opened 2015-07-17 22:56 UTC
`expect.fail()` and `should.fail()` have been added in [version 2.1.0](https://github.com/chaijs/chai/releases/tag/2.1.0). Although they both have a docstring ([docstring for `expect`](https://github.com/chaijs/chai/blob/e4286f81f4a1edef7dee74f79f1883be7ab3d0e4/lib/chai/interface/expect.js#L13) and [docstring for `should`](https://github.com/chaijs/chai/blob/e4286f81f4a1edef7dee74f79f1883be7ab3d0e4/lib/chai/interface/should.js#L42)), they cannot be found in the documentation. Their [`assert` counterpart](https://github.com/chaijs/chai/blob/5520c1690cd2aec9591adfcf90c8c84be183b427/lib/chai/interface/assert.js#L45), however, can be found [here](http://chaijs.com/api/assert/#fail).

That would be very useful for plugin developers :-)

**Comment by keithamus** [comment] 2015-07-18 20:10
Thanks @astorije. The docs are available in the code, they just haven't been run through the website yet :cry: 

Just like #488 I'll close this. Please head on over to chaijs/chai-docs#74 and chaijs/chai-docs#34 to help out if you can.

**Comment by alexbooker** [comment] 2016-04-08 11:55
This still isn't documented as far as I can tell :cry:

**Comment by lucasfcosta** [comment] 2016-04-08 12:13
I think it may be because the docs for `expect/should` are generated based on the [`assertions.js`](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js) file instead of the interface files.
Maybe adding `.fail` to the same namespace as the other assertions would be enough, but I'm not sure about it, I'd need to take a further look at [`dox` docs](https://github.com/tj/dox) (lol) to make sure.

**Comment by keithamus** [comment] 2016-04-08 13:12
Looks like this is a small bug with the docs I suppose. 

The way the docs work right now, is that the BDD (expect/should) pages set yaml front matter of `api_namespace` to `BDD` (https://github.com/chaijs/chai-docs/blob/gh-pages/api/bdd.md). As @lucasfcosta points out - the api page then iterates through all of the data generated from dox 
(found here https://github.com/chaijs/chai-docs/blob/gh-pages/_data/chai.json) and if the namespace matches (in this case, `BDD`) then that doc gets rendered. So for example `.a(type)` (docs in code are here: https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L131-L160) gets rendered here: http://chaijs.com/api/bdd/#atype. 

The problem is that should.fail has a `@namespace` of `Should` (https://github.com/chaijs/chai/blob/master/lib/chai/interface/should.js#L44-L56), and expect.fail has `Expect` as the `@namespace`.

The easiest way to fix: just change the `@namespace` in the `.fail` methods to `BDD`.

**Comment by lucasfcosta** [comment] 2016-04-08 15:45
Seems good, I'm gonna do it this afternoon then, this seems very important for our users.

**Closed** 2016-04-09 07:49 UTC
Labels: bug, docs, easy-fix, pull-request-wanted

**Comment by alexbooker** [comment] 2016-05-24 21:16
Hi :wave:

I went looking for `expect.fail()` again today but I still can't find it in the documentation.

Am I blind?

**Comment by keithamus** [comment] 2016-05-24 21:37
Hey @alexbooker we have yet to release the update docs. It'll happen in the next few weeks, rest assured.

**Comment by alexbooker** [comment] 2016-05-24 21:51
@keithamus Thanks for the update.

Please keep up the top-notch work :smile:

**Comment by gasi** [comment] 2016-09-29 22:23
FYI, I just checked but couldn’t find it either. Glad it exists 😄

**Comment by erikerikson** [comment] 2017-11-22 00:04
First two arguments are still not documented as optional:
http://chaijs.com/api/bdd/#method_fail
