### ISSUE TITLE
Using Mocha framework with Appium for automation, I am also using chai should for assertions, but when they fail mocha waits for the time out and does not throw the assertion error

### ISSUE THREAD

**Issue by blueice349** [chaijs/chai#656] opened 2016-04-01 01:29 UTC
Sample code:

File 1 where should is being called:

```js
var wd = require("wd");

require('colors');
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);
var should = chai.should();
chaiAsPromised.transferPromiseness = wd.transferPromiseness;

exports.should = should;
```

File 2 where I am using a should assertion:

```js
'use strict';

require( 'colors' );
require( '../../helpers/setup' );
var alerts   = require( '../../helpers/alerts' );
var assert   = require( 'assert' );
//var expect   = require( 'expect' );
var caps     = require( '../../helpers/caps' );
var config   = require( '../../helpers/Config' );
var commons  = require( '../../helpers/Commons' );
var elements = require( '../../helpers/elements' );
var login    = require( '../../helpers/loginTable' );
var Store    = require( '../../helpers/Store' );

var driver = config.driver;

var truckOption;
var clockInOption;
var userRole;
var userName;
var name;
var permissionGranted;
var newJob;

describe( 'Start login Process'.green, function() {

	it( 'should login'.green, function( done ) {
		config.loginTest = true;
		return driver
		.elementByName( elements.loginScreen.client_account )
		.isDisplayed().should.eventually.be.true
		.elementByName( elements.loginScreen.user_name )
		.isDisplayed().should.eventually.be.true
		.elementByName( elements.loginScreen.password )
		.isDisplayed().should.eventually.be.true
		.elementByName( elements.loginScreen.login_button )
		.isDisplayed().should.eventually.be.true
		.elementByName( elements.loginScreen.accept_terms )
		.isDisplayed().should.eventually.be.true
		.elementByName( elements.loginScreen.client_account
```

So lets say 1st element is not displayed or returns false, should sees that and does not move on with the test, but at the same time does not throw the error why it failed or didnt move on

**Comment by meeber** [comment] 2016-04-29 18:00
Hi @blueice349, apologies for the delay. Is this still an outstanding issue for you?

**Comment by blueice349** [comment] 2016-05-31 01:08
Yes there is still and issue with not showing where in the test the
assertion was

On Monday, May 30, 2016, Grant Snodgrass <notifications@github.com> wrote:

> Closed #656 <https://github.com/chaijs/chai/issues/656>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/chaijs/chai/issues/656#event-676403730>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/APTtuDWy-xKDODEv-VhxRjVO3bh8sw7gks5qG3r1gaJpZM4H9UIJ>
> .
>


-- 

[image: logo] <http://omadi.com/>

Mike Meyer Quality Assurance Software Tester

t. 855-298-4188 | m. 904-579-6418

Omadi.com <http://omadi.com/> | Omadi Help Center
<https://omadi.zendesk.com>

<http://www.facebook.com/OmadiMobileManagement>
<http://www.linkedin.com/company/omadi> <http://twitter.com/OmadiSoftware>
<http://www.youtube.com/channel/UCbj5Pm1zWjXdxX-VlplLFsA>
<https://plus.google.com/107871565889047763439> <http://omadi.com/blog>

**Comment by meeber** [comment] 2016-05-31 03:17
@blueice349 There's so much going on in this example, Would it be possible to provide a smaller, standalone example demonstrating the problem? Also, do you think Appium is a key part of the equation, or do you suspect the issue could be reproduced without it?

**Comment by blueice349** [comment] 2016-05-31 03:23
I believe it could be reproduced my using the following 
somElement.isDisplayed().should.eventually.be.true;

Make it so the element is not displayed or use a fake element where he assertion would fail. It won't show what file or line # where the test failed

**Comment by blueice349** [comment] 2016-05-31 14:21
log:

![screen shot 2016-05-31 at 8 26 06 am](https://cloud.githubusercontent.com/assets/16051640/15677702/a4fa6462-2708-11e6-8380-538488db00e7.png)

**Comment by keithamus** [comment] 2016-05-31 14:22
@blueice349 looks like it's failing because the promise has resolved to be `true`.

**Comment by keithamus** [comment] 2016-05-31 14:23
@blueice349 I'd recommend writing a small reduced test case, this will help us work out what the issue is. If you could please make a little github repo with a package.json which has the right dependencies, and one single test which fails in the way you expect it to - we can then install it on our local machines and reproduce the error for ourselves.

**Comment by blueice349** [comment] 2016-05-31 14:23
it was expecting false, but was true, but my issue is the log does not show where it failed in the file

**Comment by blueice349** [comment] 2016-05-31 14:26
Let me work on that.

**Comment by blueice349** [comment] 2016-05-31 15:12
So I created a sample test, but I cant use the eventually in that test, I think it has to do with using eventually?

**Comment by meeber** [comment] 2016-05-31 18:09
Hi @blueice349. Thank you for working on a sample test.

Could you clarify what you mean when you say:
> but I cant use the eventually in that test

`.eventually` is provided by the [chai-as-promised](https://github.com/domenic/chai-as-promised) library.

**Comment by blueice349** [comment] 2016-06-01 21:40
let me get you a sample file and let you run it one second

**Comment by blueice349** [comment] 2016-06-01 21:47
https://github.com/blueice349/Automation/tree/fix-chai/common/SampleTest

to run the test: open terminal got to the location of rep and type:  mocha moch

**Comment by blueice349** [comment] 2016-06-01 21:48
First issue with this test is getting it to pass using .eventually second issue is getting it to fail using . eventually

**Comment by meeber** [comment] 2016-06-01 23:09
@blueice349 Thanks for the example test!

You're right, there does appear to be an issue with failed tests involving `chai-as-promised` not displaying a proper stack trace.

I suspect this is related to: https://github.com/domenic/chai-as-promised/issues/118

I'm not sure yet if this a problem with mocha, chai, or chai-as-promised, but will investigate.

By the way, the reason your example test isn't working is because `.eventually` only works with `promises`, which the `var sampleTest` in your example is not.

I've created a new standalone test case below in the spirit of your example which demonstrates the lack of a stack trace:

```js
let chai = require("chai");
let chaiAsPromised = require("chai-as-promised");

chai.use(chaiAsPromised);
chai.should();

var sampleTest = new Promise(function (resolve, reject) {
  setTimeout(function () {
    resolve(true);
  }, 1000);
});

describe('sampleTest', function () {
  it('success', function() {
    return sampleTest.should.eventually.equal(true);
  });

  it('failure', function () {
    return sampleTest.should.eventually.equal(false);
  });
});
```

> The output of this is:
> 
>   sampleTest
>     1) failure
>     ✓ success
> 
> 
>   1 passing (1s)
>   1 failing
> 
>   1) sampleTest failure:
> 
>       AssertionError: expected true to equal false
>       + expected - actual
> 
>       -true
>       +false
> 
> 
> 
> 
> 
> npm ERR! Test failed.  See above for more details.

**Comment by meeber** [comment] 2016-06-02 03:00
Poked around for a bit. I think we might be dealing with a larger issue here regarding native Promises and stack traces.

I was able to get correct stack traces in the above examples by using [bluebird](https://github.com/petkaantonov/bluebird) Promises with the `longStackTraces` option.

But no luck yet with native Promises after limited experimentation.

**Comment by meeber** [comment] 2016-06-02 13:43
@keithamus @lucasfcosta I'd love your guys opinion on this one. Seems like a tricky issue.

Here are some tests with the latest versions of node, mocha, chai, chai-as-promised, and bluebird.

Note that the only combination that doesn't produce useful a stack trace is native promises + chai-as-promised (regardless of `chai.config.includeStack` setting).

```js
var BBPromise = require('bluebird');
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');

BBPromise.config({longStackTraces: true});

chai.use(chaiAsPromised);
chai.should();

var expect = chai.expect;

describe('promise', function () {
  afterEach(function () {
    chai.config.includeStack = false;
  });

  it('native Promise', function () {
    var promise = Promise.resolve(42);
    return promise.then(function (val) {
      expect(val).to.equal(43);
    });
  });

  it('native Promise; chai-as-promised', function () {
    var promise = Promise.resolve(42);
    return expect(promise).to.eventually.equal(43);
  });

  it('native Promise; chai-as-promised; chai.config.includeStack', function () {
    chai.config.includeStack = true;

    var promise = Promise.resolve(42);
    return expect(promise).to.eventually.equal(43);
  });

  it('bluebird Promise; longStackTraces', function () {
    var promise = BBPromise.resolve(42);
    return promise.then(function (val) {
      expect(val).to.equal(43);
    });
  });

  it('bluebird Promise; chai-as-promised; longStackTraces', function () {
    var promise = BBPromise.resolve(42);
    return expect(promise).to.eventually.equal(43);
  });
});
```

Results:

```
promise
    1) native Promise
    2) native Promise; chai-as-promised
    3) native Promise; chai-as-promised; chai.config.includeStack
    4) bluebird Promise; longStackTraces
    5) bluebird Promise; chai-as-promised; longStackTraces


  0 passing (26ms)
  5 failing

  1) promise native Promise:

      AssertionError: expected 42 to equal 43
      + expected - actual

      -42
      +43

      at test/index.js:20:22

  2) promise native Promise; chai-as-promised:

      AssertionError: expected 42 to equal 43
      + expected - actual

      -42
      +43



  3) promise native Promise; chai-as-promised; chai.config.includeStack:

      AssertionError: expected 42 to equal 43
      + expected - actual

      -42
      +43

      at assertEqual (node_modules/chai/lib/chai/core/assertions.js:487:12)
      at ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at node_modules/chai-as-promised/lib/chai-as-promised.js:308:26

  4) promise bluebird Promise; longStackTraces:

      AssertionError: expected 42 to equal 43
      + expected - actual

      -42
      +43

      at test/index.js:39:22
  From previous event:
      at Context.<anonymous> (test/index.js:38:20)

  5) promise bluebird Promise; chai-as-promised; longStackTraces:

      AssertionError: expected 42 to equal 43
      + expected - actual

      -42
      +43

      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:307:16)
      at .<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:21)
      at ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at Context.<anonymous> (test/index.js:45:42)



npm ERR! Test failed.  See above for more details.
```

**Comment by meeber** [comment] 2016-06-27 10:47
As mentioned above, the root of this problem is with promises and asynchronicity in general. I've posted a hacky solution at https://github.com/domenic/chai-as-promised/pull/155 but it doesn't seem likely it'll be merged. Nothing we can do about it in Chai core, sorries ;(

**Closed by meeber** 2016-06-27 10:47 UTC
