### ISSUE TITLE
sameMembers reports members that are actual correct

### ISSUE THREAD

**Issue by LokiMidgard** [chaijs/chai#1146] opened 2018-03-07 14:53 UTC
I've noticed that `sameMembers` reports members that are included in the expected and actual because they are not on the same position in the array.

Sample:

```c#
let actual = [
    'a',
    'b',
    'c',
    'd',
    'e',
];
let expected = [
    'd',
    'c',
    'b',
    'a',
];
assert.sameMembers(actual, expected, 'Fails');
```
This should and will fail because `e` is not in expected. However the output will hint at every element but `a`

```c#
      Fails
      + expected - actual

       [
      +  "d"
      +  "c"
      +  "b"
         "a"
      -  "b"
      -  "c"
      -  "d"
      -  "e"
       ]
```

I would expect an output simular to following, because I didn't used `sameOrderedMembers`:

```c#

      Fails
      + expected - actual

       [
         "a"
         "b"
         "c"
         "d"
      -  "e"
       ]
```
For completness, the assert does not fail if only the order elements is different, but all and not more elements are in the actuall array.

**Comment by meeber** [comment] 2018-03-21 01:55
Just to be clear: the diff is generated by your test runner (e.g., Mocha), not by Chai. However, Chai provides the `expected` and `actual` objects that are used by your test runner to generate the diff. There's currently not a good way for Chai to advise the test runner on how the diff should be generated/formatted, other than to manipulate the `expected` and `actual` values contained in the `AssertionError`. (In the future, we hope for Chai to have more influence over the diff, as discussed in #1120.)

I agree that the expected output you provided in your example is more useful than the current output. Chai could achieve this by sorting the expected and actual arrays in the case of unordered `members` assertions. Unfortunately, with the way Chai currently works, there'd be a performance penalty to implementing this change right now, because the `expected` and `actual` objects are constructed even in the case of a passing test. In a future version of Chai, we'd only need to perform the sorting in the case of a failed assertion. (Or, better yet, generate the diff ourselves, or at least provide information to the test runner on how to do it.)

Given these current issues & limitations in Chai related to diffing, I'm not sure the value of this change is high enough to justify the cost.

**Comment by keithamus** [comment] 2018-06-09 16:10
Hey @LokiMidgard thanks for this issue!

We'll be spending a lot of time with the new version of chai to address issues like this. I think right now this issue will likely be swept up with a bunch of new refactoring work on our inspection utilities.

I think we can close this as it'll be implicitly resolved by a new major release of `loupe` which will be a major rewrite.

**Closed by keithamus** 2018-06-09 16:10 UTC

**Comment by vassudanagunta** [comment] 2024-06-21 17:30
@keithamus, @meeber,

It's been 6 years, and it looks like the aforementioned work did not end up addressing this. Can this be re-opened? Or should I create a new issue?

**Comment by keithamus** [comment] 2024-06-24 11:06
Sure please file a new issue with a concrete reproduction. Thanks!
