### ISSUE TITLE
Buffer is not recognized as an object

### ISSUE THREAD

**Issue by mirayashi** [chaijs/chai#1541] opened 2023-09-28 13:32 UTC
Let the following test:

```js
const buf = Buffer.alloc(0)
expect(buf).to.be.an('object')
```

Expected result: the test should pass because `expect(typeof buf).to.equal('object')` does

Actual result: it fails

chai version 4.3.9

**Comment by keithamus** [comment] 2023-09-28 14:56
`.to.be.an` effectively checks the `Symbol.toStringTag` of the object. If you want to assert on the `typeof`, then you should use `expect(typeof buf).to.equal('object')`.

I'll close this as it's not a bug within chai, it's working as intended.

**Closed by keithamus** 2023-09-28 14:56 UTC
