### ISSUE TITLE
API for QUnit support

### ISSUE THREAD

**Issue by lolmaus** [chaijs/chai#1132] opened 2018-01-29 14:44 UTC
Previously, it was possible to use Chai with QUnit via ugly hacks. With Chai 4, even ugliest hacks are impossible.

Please provide an API for Chai to be usable with QUnit.

PS QUnit has a great, rich-featured HTML reporter out of the box, and is a default test suite in the EmberJS ecosystem.

**Comment by Turbo87** [comment] 2018-01-29 14:51
The main differences between QUnit and almost any other test system are that it a) also records passed assertions and b) it keeps running the test code after failed assertions.

Essentially this means that we would need a hook that prevents the usual `AssertionError` from being thrown and instead calls some QUnit API whether passing or not.

With Chai 3 it was possible to hack this together but something in Chai 4 made this much harder. I'm trying to remember what exactly it was and I think it was related to the `Proxy` usage, but I'm not sure. Last time I played around with this was a few months ago.

The old hacked together code for Chai 3 is available at https://github.com/ember-cli/ember-cli-chai/blob/v0.4.3/addon/qunit.js

**Comment by keithamus** [comment] 2018-01-29 15:10
Thanks for the issue @lolmaus 

Proxies can be disabled - if they're what is causing the problem. If there is something that Proxies are preventing you doing, then please do provide some code that reproduces the problem, and we'll try to fix it.

Otherwise, you might be interested in following #585 which will generalise the way assertions are created, and hopefully lead to the ability for chai to integrate with test runners which do not expect it to throw errors.

**Comment by keithamus** [comment] 2018-06-09 16:20
Hey @lolmaus

Thank you for your time in reporting this. I'm going to close this, because we're about to put a bunch of work into refactoring chai for chai 5 - which will implicitly fix this issue. There's nothing really that is actionable from this one issue, but in general chai 5 will support this kind of stuff.

**Closed by keithamus** 2018-06-09 16:20 UTC
