### ISSUE TITLE
Timeout when expectation fails

### ISSUE THREAD

**Issue by kouno** [chaijs/chai#543] opened 2015-10-27 15:33 UTC
Here is the shortest version I could do to show this error:

```javascript
describe("get to api.github.com", function () {
  var result;

  beforeEach(function () {
    result = $.get('https://api.github.com/');
  });

  it("fails with an expection not met error", function(done) {
    result.done(function(data) {
      expect(false).toBe(true);
      done();
    });

    result.fail(done.fail);
  }, 10000);

  it("fails with a timeout", function(done) {

    result.done(function(data) {
      window.expect = chai.expect;
      expect(false).to.be(true);
      // done is never executed
      done();
    });

    result.fail(done.fail);
  }, 10000);
});
```

Both should return: `Failure/Error: Expected false to be true.`

They indeed fail but the one using chai fails with a timeout. The problem is that this makes the test suite a lot slower when it could fail faster.

**Comment by keithamus** [comment] 2015-10-28 20:45
Hey @kouno thanks for the issue.

What test runner are you using? It looks like mocha but I'm not familiar with `done.fail`. Mocha's async tests should stop executing when an uncaught exception occurs.

Are you also using jQuery? Is that what `$.get` is? It's been a while since I've used jQuery but aren't the ajax calls thenables (i.e. they have a `.then` and `.catch` like a real Promise does)? If that is the case I'd recommend using the thenable version instead, as Mocha can deal with it a lot easier and thennable call backs are try/caught for free, and they're also more succinct:

```js
it("fails with an expection not met error", function() {
  return result.then(function(data) {
    expect(false).toBe(true);
  });
}, 10000);
```

**Comment by kouno** [comment] 2015-10-28 21:06
> It looks like mocha but I'm not familiar with done.fail

`done.fail` is part of Jasmine: http://jasmine.github.io/2.3/introduction.html.

> Are you also using jQuery? Is that what $.get is? It's been a while since I've used jQuery but aren't the ajax calls thenables (i.e. they have a .then and .catch like a real Promise does)?

Yes it is jQuery, but changing it to use `then` which may catch the exception won't fix the problem. If done() is never executed, it will still fail with a timeout.

Let's say I remove the jQuery part:

```javascript
it("fails with a timeout", function(done) {
    setTimeout(function() {
      window.expect = chai.expect;
      expect(false).to.be(true);
      // done is never executed
      done();
    },100);
  }, 10000);
```

In the above code, using `chai.expect`, it will timeout after 10000ms. Using the regular `expect(false). toBe (true)` from Jasmine would still execute `done()` and finish after a 100ms.

**Comment by keithamus** [comment] 2015-10-29 10:56
It looks like Jasmine's test runner is not compatible with chai. I would expect Jasmine to catch uncaught errors in async tests, but it seems as though it is not doing that - or at least not doing it properly. I'd recommend using another test runner, such as [Mocha](https://mochajs.org/), [Tape](https://github.com/substack/tape), [Vows](http://vowsjs.org/), [Nodeunit](https://github.com/caolan/nodeunit), or [Hydro](https://github.com/hydrojs/hydro). All of these runners should be compatible with [CommonJS Unit Testing/1.0](http://wiki.commonjs.org/wiki/Unit_Testing/1.0) and should catch on errors from any other CommonJS assertion framework, including Chai.

Alternatively you could try filing this as an issue on [Jasmine's issue tracker](https://github.com/jasmine/jasmine/issues). They might be keen on fixing this.

I'm quite confident that there's nothing that Chai can do to fix this, and that it is in the hands of Jasmine, and as such I'll close this issue. If you find any evidence to the contrary, please let me know and I can re-open it.

---

P.S.

> Yes it is jQuery, but changing it to use then which may catch the exception won't fix the problem. If done() is never executed, it will still fail with a timeout.

One of the cool features about Mocha is that you can return a Promise and Mocha will do all the hard work for you - so you don't even need to pass a `done()`! My example:

> ```js
it("fails with an expection not met error", function() {
  return result.then(function(data) {
    expect(false).toBe(true);
  });
});
```

Is a perfectly valid async test in Mocha's framework. It saves a bunch of time and code! I'd recommend you try it :smile:

**Closed by keithamus** 2015-10-29 10:56 UTC

**Comment by kouno** [comment] 2015-10-29 11:55
Thanks for the feedback! :smile:

I actually was not sure which behavior was meant to be right, but I thought at least I would raise the issue. I'll try to fill this issue on Jasmine later.

**Comment by franciscop** [comment] 2016-04-27 14:32
I am not sure if that's the reason, I'm not using Jasmine and getting this error nonetheless. I'm following almost strictly [phantomjs-node](https://github.com/amir20/phantomjs-node) tutorial, but adding a callback that will be passed the content. Then when something inside the callback fails, the promise catches it:

```js
...then(function(content){
    sitepage.close();
    phInstance.exit();
    $ = cheerio.load(content);
    callback(content, status, $);
  }).catch(function(e){
    console.log("Error:", e);
    phInstance.exit();
  });
```

I was getting many problems since I didn't write that `catch()` and everything was just silently ignored. Now I just show the error and that `phInstance.exit()` seems to make it work better (also I changed the order of the functions, since the closing and exit in the `then()` were after the callback).

Got here searching for the issue. So basically, sometimes you can wrap the exception with code that will handle it almost by accident.

**Comment by piotr-s-brainhub** [comment] 2016-08-30 16:24
I have the same issue with mocha.

**Comment by meeber** [comment] 2016-08-30 23:28
@piotr-s-brainhub If you're running into an issue with Mocha that appears similar, then I suspect something else is going on. Please open a new issue with a standalone example demonstrating the unexpected behavior and we'll be happy to take a look.

**Comment by piotr-s-brainhub** [comment] 2016-08-31 07:58
It works well when I return a Promise. I had a problem because in `then` there was another Promise but I solved it with `return Promise.all([ ... ]).then(() => {...}).then() => { ... expect(...)... });`
