### ISSUE TITLE
How to implement json-diff like mocha ?

### ISSUE THREAD

**Issue by bertho-zero** [chaijs/chai#1060] opened 2017-10-05 10:32 UTC
It is currently not possible to see the differences of an object/table directly with the chai configuration, which makes debugging tests really complicated when dealing with large objects.

How is it possible to integrate json-diff for all AssertionError, like with mocha ?
Do you intend to make this natively configurable with chai ?

**Comment by keithamus** [comment] 2017-10-05 11:15
Hey @bertho-zero thanks for the issue.

Chai doesn't do any diffing at current. It passes the `actual` and `expected` fields inside the `AssertionError` object for the reporter to do diffing. If you aren't using mocha, then whatever test runner you are using will need to support diffing by introspecting the `error.actual` and `error.expected` properties.

I'll close this issue; as its not a bug within our code. Feel free to continue the conversation though, and we can always re-open the issue if there is a need to :)

**Closed by keithamus** 2017-10-05 11:15 UTC

**Comment by bertho-zero** [comment] 2017-10-05 13:02
Finally I used this chai plugin that works perfectly: https://www.npmjs.com/package/chai-jest-diff
