### ISSUE TITLE
Deep equals -0 array comparison

### ISSUE THREAD

**Issue by dherre3** [chaijs/chai#1176] opened 2018-07-26 17:42 UTC
**Context:**
Trying to compare array contents.
**Version:**
v4.1.2
**Example:**
```
expect([-0,-0,-0]).to.deep.equal([0,0,0]);
```
This will return:
```
AssertionError: expected [ -0, -0, -0 ] to deeply equal [ 0, 0, 0 ]
```
**More Info**:
In JavaScript -0 === 0 returns true.
In Chai the test with a single input also returns true.
i.e.
```
expect(-0).to.equal(0); //true
```

**Comment by keithamus** [comment] 2018-07-27 10:19
Hey @dherre3 thanks for this issue!

This is by design, `deep-eql` uses `Object.is` as a comparison, not `===`. This way `NaN` compares (`Object.is(NaN, NaN) === 0`) and `-0` does not (`Object.is(-0, 0) === false`). There are subtle edge cases between `-0` and `0` that mean they are not equivalent, for example `1/-0 === -Infinity` while `1/0 === Infinity`. Because of this we consider it better to use `Object.is` and fail the comparison when we see `-0`.

In Chai 5 we'll be able to change how `deep-eql` does comparison, so if you're keen to have `-0` and `0` compare and pass, then you should be able to with Chai 5.

I'm going to close this, because there is nothing for us to do right now, but rest assured this has been noted, and we'll be making sure to keep this in mind in the future.

**Closed by keithamus** 2018-07-27 10:19 UTC
