### ISSUE TITLE
Mocha blows up when trying to include `.should()`

### ISSUE THREAD

**Issue by victorbstan** [chaijs/chai#517] opened 2015-09-14 15:26 UTC
When trying to use `should` like so:

```
var chai = require("chai");
chai.should();
chai.use(require('chai-things'));
```

I get:

```
>> Mocha exploded!
>> TypeError: object is not a function
>>     at Object.<anonymous> (/Users/xxx/Code/xxx/server/api/tests/channel.routes.test.js:4:6)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at /Users/xxx/Code/xxx/node_modules/mocha/lib/mocha.js:216:27
>>     at Array.forEach (native)
>>     at Mocha.loadFiles (/Users/xxx/Code/xxx/node_modules/mocha/lib/mocha.js:213:14)
>>     at MochaWrapper.run (/Users/xxx/Code/xxx/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:51:15)
>>     at /Users/xxx/Code/xxx/node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
>>     at capture (/Users/xxx/Code/xxx/node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
>>     at Object.<anonymous> (/Users/xxx/Code/xxx/node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
>>     at Object.<anonymous> (/Users/xxx/Code/xxx/node_modules/grunt/lib/grunt/task.js:264:15)
>>     at Object.thisTask.fn (/Users/xxx/Code/xxx/node_modules/grunt/lib/grunt/task.js:82:16)
```

Removing `chai.should();` gets rid of the error. Also using `chai.should`, gets rid of the error, but as expected `should` does not work in that case.

**Comment by keithamus** [comment] 2015-09-21 08:59
Hey @victorbstan thanks for the issue.

Ideally picking your interface should go below all `.use()` calls. Other than that, everything looks fine - so I'm not sure the issue is coming from there. Could you provide more details about your code & the test harness?

**Comment by keithamus** [comment] 2015-09-28 14:03
Hey @victorbstan have you had a chance to look at this? It'd be great if we could get some more details from you, such as the code you have written for the tests.

**Comment by keithamus** [comment] 2015-11-27 12:14
Hey @victorbstan. I'm going to close this, as it's a couple of months old and I've been unable to reproduce the issue in that time. 

If you get the time to make a reduced test case, or provide us with more info or more failures around this, let me know and I can re-open this and we'll try to find out what's going on.

**Closed by keithamus** 2015-11-27 12:14 UTC
