### ISSUE TITLE
Failing to compare DOM Document structures

### ISSUE THREAD

**Issue by ThomasBracher** [chaijs/chai#628] opened 2016-02-23 22:06 UTC
I use Chai to test some browser side code and i stumble a a weird bug : on Chrome, the Dom Document structure cannot be deepEqual'd or compare, the error is : `Error: Failed to read the 'cookie' property from 'Document': Access is denied for this document.`, on Edge : `Error: Unspecified error`, but it works fine on Firefox.

You can simply reproduce the bug with this snippet:

```javascript
chai.assert.deepEqual(new DOMParser().parseFromString('<div>Hello</div>', 'text/html'), new DOMParser().parseFromString('<div
div>Hello</div>', 'text/html'));
```

I ended up using `isEqualNode` which works fines on chrome, firefox & edge.

```javascript
chai.assert.ok((new DOMParser().parseFromString('<div>Hello</div>', 'text/html')).isEqualNode(doc));
```

**Comment by keithamus** [comment] 2016-02-23 22:22
Hey @ThomasBracher thanks for the issue.

The `DOMParser` returns actual DOMElements which don't fit very well with deep equality, because they don't behave like plain javascript objects; most of their properties are non-enumerable and some properties can throw errors depending on their calling context, etc. You're seeing this with the error `Error: Failed to read the 'cookie' property from 'Document': Access is denied for this document.` - which is reproducible by the following code: `new DOMParser().parseFromString('<div>Hello</div>', 'text/html').cookie`.

You'd be much better off using a plugin that works with the DOM specifically, such as [chai-dom](https://github.com/nathanboktae/chai-dom). If it is missing assertions you'd like to see - I'd suggest filing issues with that plugin. 

Hope this helps. I'm going to close this issue as Chai core isn't designed to work with the DOM, but if you find any more issues or if you run into any more troubles, feel free to file a new issue :smile:

**Closed by keithamus** 2016-02-23 22:22 UTC
