### ISSUE TITLE
`includes` expects `undefined` When Test Fails

### ISSUE THREAD

**Issue by sambunting** [chaijs/chai#1475] opened 2022-07-27 11:26 UTC
When using `expect().to.include()` - if the expected value of the `include` doesn't match the actual value - in the console it would say it expected `undefined`.

 ```js
// Passes
const foo = ['Hello World!']
expect(foo).to.include('Hello World!');

// Fails
const foo = ['Hello!']
expect(foo).to.include('Hello World!');
```

An example console output is:
```
Expected value to strictly be equal to:
  undefined
Received:
  ["Hello!"]
  
  Message:
    expected [ 'Hello!' ] to include 'Hello World!'
  
  Difference:
    Comparing two different types of values. Expected undefined but received array.
```

I think this is just a bug more to do with the console output itself, not the functionality of the test. It's not a game-changing bug, but I did spend a bit of time trying to figure out what's wrong when it was down to me misspelling something 🙃 

Environment wise, I'm using Jest 28.1.3, and Chai 4.3.6.

**Comment by FaustXVI** [comment] 2023-01-24 10:32
Hello,
Same problem here with `matches` : 
```js
expect("Testing").to.matches(/Wrong/);
```
Using Jest 29.3.1, and Chai 4.3.7.

I also tried to rollback up to Jest 27.5.1 with chai 3.5.0 and the problem was still there.
It looks like it's an issue that is there since a while.

**Comment by koddsson** [comment] 2024-01-30 17:58
This is weird!

I can't reproduce in chai 5.0 so I'm gonna close this as fixed. Feel free to re-open if not.

**Closed by koddsson** 2024-01-30 17:58 UTC
