### ISSUE TITLE
Proposal: Ability to exclude property from `deepEqual`

### ISSUE THREAD

**Issue by sanex3339** [chaijs/chai#885] opened 2016-12-13 08:41 UTC
For example a have two AST trees, each node of these AST trees has `uniqueId` property which is random string.

Now i want to deep equal this AST trees and equal fails because `uniqueId` properties are not the same.

So, it would be nice to describe in `deepEqual` array with property names which would be ignored during `deepEqual`

![deep-equal](https://cloud.githubusercontent.com/assets/9210534/21133628/d21a06a2-c12a-11e6-818d-409ec725580c.jpg)

**Comment by lucasfcosta** [comment] 2016-12-13 10:09
Hi @sanex3339, thanks for you issue!

Your request seems to make sense to me, even though you could simply traverse the whole object using `Object.getOwnPropertyNames` + `Object.getPrototypeOf` that would be too much work in a single test.

But, when thinking about how we would do that I'm not sure there will be a clean way to create such an assertion. The only acceptable syntax that comes to my mind is `expect(objOne).to.be.deepEqual(objTwo).exceptFor('keyName')` but unfortunately we wouldn't be able to apply `exceptFor` to the `deepEqual` assertion since it comes later.

IMO that would be an useful feature to have, but only if we had a clean way of expressing that through code.

If anyone has a better idea or disagrees, please share your thoughts 😄

**Comment by sanex3339** [comment] 2016-12-13 10:12
Sadly i can't help with brain storm, but it would be nice if this feature will be implemented (with `assert` interface :smile:).

**Comment by shvaikalesh** [comment] 2016-12-13 10:14
Hey @sanex3339, thanks for the proposal.

I've tried using Chai's `.deep.equal` to compare ASTs and strongly feel that `exclude` property would be of much help to ignore whitespaces (PostCSS's `raws`) and `source`s. So definitely 👍 .

On implementation: we can add `options` object as second parameter to `.equal`.

**Comment by keithamus** [comment] 2016-12-13 12:08
FWIW I think this might be a kind of duplicate of https://github.com/chaijs/chai/issues/644. Part of the work with deep-eql's recent huge refactoring was to enable these kind of behaviour alterations within the deep-eql algo. The plan in https://github.com/chaijs/chai/issues/644 is different but I'd like to see some more discussion around that. I won't close this one, but let's keep both in mind when discussing.

**Comment by GeoffreyEmerson** [comment] 2017-07-05 16:58
@lucasfcosta - It might help to simply change the word order. It would still be very readable to say:

```expect(objOne).excluding('keyName').to.deep.equal(objTwo)```

The logic could be that the "excluding" method creates a copy of the object and deletes the named property if it exists, which is how I've just written my test now that I've thought through this problem.

**Comment by mesaugat** [comment] 2017-10-22 06:25
@GeoffreyEmerson I made a simple plugin to do something like this. Hopefully it is helpful to some. https://github.com/mesaugat/chai-exclude

**Comment by keithamus** [comment] 2018-06-09 17:14
We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.

**Closed by keithamus** 2018-06-09 17:14 UTC
Labels: more-discussion-needed

**Comment by porlov** [comment] 2019-07-23 19:43
@keithamus What is the current status of this issue?
I don't see it in roadmap anymore.

**Comment by keithamus** [comment] 2019-08-19 14:40
@porlov this will be covered by https://github.com/chaijs/chai/projects/2#card-10444260 which allows for expectations within deep-eql:

```
expect(objOne).to.eql({
  keyName1: expect.to.be.a.string(),
  keyName2: expect.to.not.exist()
})
```

**Comment by Debbielei** [comment] 2019-12-08 02:53
@keithamus could you please review your last example code.   Where should the objTwo be defined?  In the initial example / issue, there are two objects  (such as objOne and objTwo).  The goal is to compare the whole object except `uniqueId`(keyName2).
