### ISSUE TITLE
0 !== -0 in chai assertion library

### ISSUE THREAD

**Issue by apsdehal** [chaijs/chai#450] opened 2015-05-26 22:31 UTC
We have a spec that returns -0 and we compare it to 0 and chai doesn't accept that. In JavaScript 
![screen shot 2015-05-26 at 3 22 01 pm](https://cloud.githubusercontent.com/assets/3616806/7824912/fe286bf4-03bb-11e5-922a-3813263314c6.png)

0 === -0 is true as shown by the screenshot from chrome's console. https://github.com/apsdehal/globalize/blob/master/test/unit/date/tokenizer.js#L687 is the link to spec. We are using intern which uses chai under the hood. Probably, chai should fix the underlying implementation of equal assert.

**Comment by csnover** [comment] 2015-05-27 12:21
Duplicate of #223

**Closed** 2015-05-29 17:49 UTC
